% +--------------------------------------------------------------------------+
% | 'TrussMe' module version 0.0 - BSD 3-Clause License - Copyright (c) 2023 |
% | Current version authors:                                                 |
% |   Davide Stocco and Matteo Larcher.                                      |
% +--------------------------------------------------------------------------+

% Matlab generated code for system: Test_00
% This file has been automatically generated by TrussMe.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef Test_00 < TrussMe.System
  %
  % Test_00 class
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = Test_00( varargin )
      % Class constructor.

      % User data
      if (nargin == 0)
        data = [];
      elseif (nargin == 1 && isstruct(varargin{1}))
        data = varargin{1};
      else
        error('wrong number of input arguments.');
      end

      % Call superclass constructor
      this = this@TrussMe.System(data);
    end % Test_00
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K = K( ~, ~, ~ )
      % Evaluate the stiffness matrix K.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K = sparse(30, 30);
      out_K(1, 1) = 666666.6667;
      out_K(7, 1) = -666666.6667;
      out_K(2, 2) = .2222272225e11;
      out_K(6, 2) = .6666666667e11;
      out_K(8, 2) = -.2222222225e11;
      out_K(14, 2) = -500000.;
      out_K(3, 3) = .1263888889e12;
      out_K(4, 3) = -.7500000000e11;
      out_K(5, 3) = -.1333333333e12;
      out_K(9, 3) = -.8888888888e11;
      out_K(11, 3) = -.1333333333e12;
      out_K(15, 3) = -.3750000000e11;
      out_K(16, 3) = -.7500000000e11;
      out_K(3, 4) = -.7500000000e11;
      out_K(4, 4) = .2666666667e12;
      out_K(10, 4) = -.6666666667e11;
      out_K(15, 4) = .7500000000e11;
      out_K(16, 4) = .1000000000e12;
      out_K(3, 5) = -.1333333333e12;
      out_K(5, 5) = .3166666667e12;
      out_K(9, 5) = .1333333333e12;
      out_K(11, 5) = .1333333333e12;
      out_K(17, 5) = -.5000000000e11;
      out_K(2, 6) = .6666666667e11;
      out_K(6, 6) = .2000000001e12;
      out_K(8, 6) = -.6666666667e11;
      out_K(1, 7) = -666666.6667;
      out_K(7, 7) = .1244795467e11;
      out_K(8, 7) = -2304000000.;
      out_K(12, 7) = .3750000000e11;
      out_K(13, 7) = -3072144000.;
      out_K(14, 7) = 2303808000.;
      out_K(18, 7) = .1920000000e11;
      out_K(19, 7) = -9375000000.;
      out_K(25, 7) = -144000.;
      out_K(26, 7) = 192000.;
      out_K(2, 8) = -.2222222225e11;
      out_K(6, 8) = -.6666666667e11;
      out_K(7, 8) = -2304000000.;
      out_K(8, 8) = .2395123425e11;
      out_K(13, 8) = 2303808000.;
      out_K(14, 8) = -1728256000.;
      out_K(18, 8) = -.1440000000e11;
      out_K(20, 8) = -500000.;
      out_K(25, 8) = 192000.;
      out_K(26, 8) = -256000.;
      out_K(3, 9) = -.8888888888e11;
      out_K(5, 9) = .1333333333e12;
      out_K(9, 9) = .1647888889e12;
      out_K(10, 9) = -.1518000000e12;
      out_K(11, 9) = .1333333333e12;
      out_K(15, 9) = -.1920000000e11;
      out_K(16, 9) = -.3840000000e11;
      out_K(17, 9) = .2880000000e11;
      out_K(21, 9) = -.3750000000e11;
      out_K(22, 9) = -.7500000000e11;
      out_K(27, 9) = -.1920000000e11;
      out_K(28, 9) = -.3840000000e11;
      out_K(29, 9) = -.2880000000e11;
      out_K(4, 10) = -.6666666667e11;
      out_K(9, 10) = -.1518000000e12;
      out_K(10, 10) = .5002666667e12;
      out_K(15, 10) = .3840000000e11;
      out_K(16, 10) = .3680000000e11;
      out_K(17, 10) = -.5760000000e11;
      out_K(21, 10) = .7500000000e11;
      out_K(22, 10) = .1000000000e12;
      out_K(27, 10) = .3840000000e11;
      out_K(28, 10) = .3680000000e11;
      out_K(29, 10) = .5760000000e11;
      out_K(3, 11) = -.1333333333e12;
      out_K(5, 11) = .1333333333e12;
      out_K(9, 11) = .1333333333e12;
      out_K(11, 11) = .4830666667e12;
      out_K(15, 11) = -.2880000000e11;
      out_K(16, 11) = -.5760000000e11;
      out_K(17, 11) = 3200000000.;
      out_K(23, 11) = -.5000000000e11;
      out_K(27, 11) = .2880000000e11;
      out_K(28, 11) = .5760000000e11;
      out_K(29, 11) = 3200000000.;
      out_K(7, 12) = .3750000000e11;
      out_K(12, 12) = .1500000000e12;
      out_K(19, 12) = -.3750000000e11;
      out_K(7, 13) = -3072144000.;
      out_K(8, 13) = 2303808000.;
      out_K(13, 13) = 3072810667.;
      out_K(14, 13) = -2303808000.;
      out_K(18, 13) = -.1920000000e11;
      out_K(19, 13) = -666666.6667;
      out_K(2, 14) = -500000.;
      out_K(7, 14) = 2303808000.;
      out_K(8, 14) = -1728256000.;
      out_K(13, 14) = -2303808000.;
      out_K(14, 14) = .2395097825e11;
      out_K(18, 14) = .8106666668e11;
      out_K(20, 14) = -.2222222225e11;
      out_K(3, 15) = -.3750000000e11;
      out_K(4, 15) = .7500000000e11;
      out_K(9, 15) = -.1920000000e11;
      out_K(10, 15) = .3840000000e11;
      out_K(11, 15) = -.2880000000e11;
      out_K(15, 15) = .1455888889e12;
      out_K(16, 15) = .1134000000e12;
      out_K(17, 15) = -.1621333333e12;
      out_K(21, 15) = -.8888888888e11;
      out_K(23, 15) = -.1333333333e12;
      out_K(3, 16) = -.7500000000e11;
      out_K(4, 16) = .1000000000e12;
      out_K(9, 16) = -.3840000000e11;
      out_K(10, 16) = .3680000000e11;
      out_K(11, 16) = -.5760000000e11;
      out_K(15, 16) = .1134000000e12;
      out_K(16, 16) = .3834666667e12;
      out_K(17, 16) = -.5760000000e11;
      out_K(22, 16) = -.6666666667e11;
      out_K(5, 17) = -.5000000000e11;
      out_K(9, 17) = .2880000000e11;
      out_K(10, 17) = -.5760000000e11;
      out_K(11, 17) = 3200000000.;
      out_K(15, 17) = -.1621333333e12;
      out_K(16, 17) = -.5760000000e11;
      out_K(17, 17) = .3998666667e12;
      out_K(21, 17) = .1333333333e12;
      out_K(23, 17) = .1333333333e12;
      out_K(7, 18) = .1920000000e11;
      out_K(8, 18) = -.1440000000e11;
      out_K(13, 18) = -.1920000000e11;
      out_K(14, 18) = .8106666668e11;
      out_K(18, 18) = .3200000001e12;
      out_K(20, 18) = -.6666666667e11;
      out_K(7, 19) = -9375000000.;
      out_K(12, 19) = -.3750000000e11;
      out_K(13, 19) = -666666.6667;
      out_K(19, 19) = 9376333333.;
      out_K(25, 19) = -666666.6667;
      out_K(8, 20) = -500000.;
      out_K(14, 20) = -.2222222225e11;
      out_K(18, 20) = -.6666666667e11;
      out_K(20, 20) = .4444494451e11;
      out_K(24, 20) = .6666666667e11;
      out_K(26, 20) = -.2222222225e11;
      out_K(9, 21) = -.3750000000e11;
      out_K(10, 21) = .7500000000e11;
      out_K(15, 21) = -.8888888888e11;
      out_K(17, 21) = .1333333333e12;
      out_K(21, 21) = .2152777778e12;
      out_K(22, 21) = .7500000000e11;
      out_K(27, 21) = -.8888888888e11;
      out_K(29, 21) = -.1333333333e12;
      out_K(9, 22) = -.7500000000e11;
      out_K(10, 22) = .1000000000e12;
      out_K(16, 22) = -.6666666667e11;
      out_K(21, 22) = .7500000000e11;
      out_K(22, 22) = .3333333333e12;
      out_K(28, 22) = -.6666666667e11;
      out_K(11, 23) = -.5000000000e11;
      out_K(15, 23) = -.1333333333e12;
      out_K(17, 23) = .1333333333e12;
      out_K(23, 23) = .5833333334e12;
      out_K(27, 23) = .1333333333e12;
      out_K(29, 23) = .1333333333e12;
      out_K(20, 24) = .6666666667e11;
      out_K(24, 24) = .2000000001e12;
      out_K(26, 24) = -.6666666667e11;
      out_K(7, 25) = -144000.;
      out_K(8, 25) = 192000.;
      out_K(19, 25) = -666666.6667;
      out_K(25, 25) = 810666.6667;
      out_K(26, 25) = -192000.;
      out_K(7, 26) = 192000.;
      out_K(8, 26) = -256000.;
      out_K(20, 26) = -.2222222225e11;
      out_K(24, 26) = -.6666666667e11;
      out_K(25, 26) = -192000.;
      out_K(26, 26) = .2222247825e11;
      out_K(9, 27) = -.1920000000e11;
      out_K(10, 27) = .3840000000e11;
      out_K(11, 27) = .2880000000e11;
      out_K(21, 27) = -.8888888888e11;
      out_K(23, 27) = .1333333333e12;
      out_K(27, 27) = .1080888889e12;
      out_K(28, 27) = .3840000000e11;
      out_K(29, 27) = .1621333333e12;
      out_K(9, 28) = -.3840000000e11;
      out_K(10, 28) = .3680000000e11;
      out_K(11, 28) = .5760000000e11;
      out_K(22, 28) = -.6666666667e11;
      out_K(27, 28) = .3840000000e11;
      out_K(28, 28) = .1834666667e12;
      out_K(29, 28) = .5760000000e11;
      out_K(9, 29) = -.2880000000e11;
      out_K(10, 29) = .5760000000e11;
      out_K(11, 29) = 3200000000.;
      out_K(21, 29) = -.1333333333e12;
      out_K(23, 29) = .1333333333e12;
      out_K(27, 29) = .1621333333e12;
      out_K(28, 29) = .5760000000e11;
      out_K(29, 29) = .3498666667e12;
    end % K
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_ff = K_ff( ~, ~, ~ )
      % Evaluate the stiffness matrix K_ff.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_ff = sparse(15, 15);
      out_K_ff(1, 1) = .2000000001e12;
      out_K_ff(3, 1) = -.6666666667e11;
      out_K_ff(2, 2) = .1244795467e11;
      out_K_ff(3, 2) = -2304000000.;
      out_K_ff(7, 2) = .3750000000e11;
      out_K_ff(8, 2) = 2303808000.;
      out_K_ff(9, 2) = .1920000000e11;
      out_K_ff(10, 2) = -9375000000.;
      out_K_ff(1, 3) = -.6666666667e11;
      out_K_ff(2, 3) = -2304000000.;
      out_K_ff(3, 3) = .2395123425e11;
      out_K_ff(8, 3) = -1728256000.;
      out_K_ff(9, 3) = -.1440000000e11;
      out_K_ff(11, 3) = -500000.;
      out_K_ff(4, 4) = .1647888889e12;
      out_K_ff(5, 4) = -.1518000000e12;
      out_K_ff(6, 4) = .1333333333e12;
      out_K_ff(12, 4) = -.3750000000e11;
      out_K_ff(13, 4) = -.7500000000e11;
      out_K_ff(4, 5) = -.1518000000e12;
      out_K_ff(5, 5) = .5002666667e12;
      out_K_ff(12, 5) = .7500000000e11;
      out_K_ff(13, 5) = .1000000000e12;
      out_K_ff(4, 6) = .1333333333e12;
      out_K_ff(6, 6) = .4830666667e12;
      out_K_ff(14, 6) = -.5000000000e11;
      out_K_ff(2, 7) = .3750000000e11;
      out_K_ff(7, 7) = .1500000000e12;
      out_K_ff(10, 7) = -.3750000000e11;
      out_K_ff(2, 8) = 2303808000.;
      out_K_ff(3, 8) = -1728256000.;
      out_K_ff(8, 8) = .2395097825e11;
      out_K_ff(9, 8) = .8106666668e11;
      out_K_ff(11, 8) = -.2222222225e11;
      out_K_ff(2, 9) = .1920000000e11;
      out_K_ff(3, 9) = -.1440000000e11;
      out_K_ff(8, 9) = .8106666668e11;
      out_K_ff(9, 9) = .3200000001e12;
      out_K_ff(11, 9) = -.6666666667e11;
      out_K_ff(2, 10) = -9375000000.;
      out_K_ff(7, 10) = -.3750000000e11;
      out_K_ff(10, 10) = 9376333333.;
      out_K_ff(3, 11) = -500000.;
      out_K_ff(8, 11) = -.2222222225e11;
      out_K_ff(9, 11) = -.6666666667e11;
      out_K_ff(11, 11) = .4444494451e11;
      out_K_ff(15, 11) = .6666666667e11;
      out_K_ff(4, 12) = -.3750000000e11;
      out_K_ff(5, 12) = .7500000000e11;
      out_K_ff(12, 12) = .2152777778e12;
      out_K_ff(13, 12) = .7500000000e11;
      out_K_ff(4, 13) = -.7500000000e11;
      out_K_ff(5, 13) = .1000000000e12;
      out_K_ff(12, 13) = .7500000000e11;
      out_K_ff(13, 13) = .3333333333e12;
      out_K_ff(6, 14) = -.5000000000e11;
      out_K_ff(14, 14) = .5833333334e12;
      out_K_ff(11, 15) = .6666666667e11;
      out_K_ff(15, 15) = .2000000001e12;
    end % K_ff
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_fs = K_fs( ~, ~, ~ )
      % Evaluate the stiffness matrix K_fs.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_fs = sparse(15, 15);
      out_K_fs(2, 1) = -666666.6667;
      out_K_fs(1, 2) = .6666666667e11;
      out_K_fs(3, 2) = -.2222222225e11;
      out_K_fs(8, 2) = -500000.;
      out_K_fs(4, 3) = -.8888888888e11;
      out_K_fs(6, 3) = -.1333333333e12;
      out_K_fs(5, 4) = -.6666666667e11;
      out_K_fs(4, 5) = .1333333333e12;
      out_K_fs(6, 5) = .1333333333e12;
      out_K_fs(2, 6) = -3072144000.;
      out_K_fs(3, 6) = 2303808000.;
      out_K_fs(8, 6) = -2303808000.;
      out_K_fs(9, 6) = -.1920000000e11;
      out_K_fs(10, 6) = -666666.6667;
      out_K_fs(4, 7) = -.1920000000e11;
      out_K_fs(5, 7) = .3840000000e11;
      out_K_fs(6, 7) = -.2880000000e11;
      out_K_fs(12, 7) = -.8888888888e11;
      out_K_fs(14, 7) = -.1333333333e12;
      out_K_fs(4, 8) = -.3840000000e11;
      out_K_fs(5, 8) = .3680000000e11;
      out_K_fs(6, 8) = -.5760000000e11;
      out_K_fs(13, 8) = -.6666666667e11;
      out_K_fs(4, 9) = .2880000000e11;
      out_K_fs(5, 9) = -.5760000000e11;
      out_K_fs(6, 9) = 3200000000.;
      out_K_fs(12, 9) = .1333333333e12;
      out_K_fs(14, 9) = .1333333333e12;
      out_K_fs(2, 10) = -144000.;
      out_K_fs(3, 10) = 192000.;
      out_K_fs(10, 10) = -666666.6667;
      out_K_fs(2, 11) = 192000.;
      out_K_fs(3, 11) = -256000.;
      out_K_fs(11, 11) = -.2222222225e11;
      out_K_fs(15, 11) = -.6666666667e11;
      out_K_fs(4, 12) = -.1920000000e11;
      out_K_fs(5, 12) = .3840000000e11;
      out_K_fs(6, 12) = .2880000000e11;
      out_K_fs(12, 12) = -.8888888888e11;
      out_K_fs(14, 12) = .1333333333e12;
      out_K_fs(4, 13) = -.3840000000e11;
      out_K_fs(5, 13) = .3680000000e11;
      out_K_fs(6, 13) = .5760000000e11;
      out_K_fs(13, 13) = -.6666666667e11;
      out_K_fs(4, 14) = -.2880000000e11;
      out_K_fs(5, 14) = .5760000000e11;
      out_K_fs(6, 14) = 3200000000.;
      out_K_fs(12, 14) = -.1333333333e12;
      out_K_fs(14, 14) = .1333333333e12;
    end % K_fs
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_sf = K_sf( ~, ~, ~ )
      % Evaluate the stiffness matrix K_sf.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_sf = sparse(15, 15);
      out_K_sf(2, 1) = .6666666667e11;
      out_K_sf(1, 2) = -666666.6667;
      out_K_sf(6, 2) = -3072144000.;
      out_K_sf(10, 2) = -144000.;
      out_K_sf(11, 2) = 192000.;
      out_K_sf(2, 3) = -.2222222225e11;
      out_K_sf(6, 3) = 2303808000.;
      out_K_sf(10, 3) = 192000.;
      out_K_sf(11, 3) = -256000.;
      out_K_sf(3, 4) = -.8888888888e11;
      out_K_sf(5, 4) = .1333333333e12;
      out_K_sf(7, 4) = -.1920000000e11;
      out_K_sf(8, 4) = -.3840000000e11;
      out_K_sf(9, 4) = .2880000000e11;
      out_K_sf(12, 4) = -.1920000000e11;
      out_K_sf(13, 4) = -.3840000000e11;
      out_K_sf(14, 4) = -.2880000000e11;
      out_K_sf(4, 5) = -.6666666667e11;
      out_K_sf(7, 5) = .3840000000e11;
      out_K_sf(8, 5) = .3680000000e11;
      out_K_sf(9, 5) = -.5760000000e11;
      out_K_sf(12, 5) = .3840000000e11;
      out_K_sf(13, 5) = .3680000000e11;
      out_K_sf(14, 5) = .5760000000e11;
      out_K_sf(3, 6) = -.1333333333e12;
      out_K_sf(5, 6) = .1333333333e12;
      out_K_sf(7, 6) = -.2880000000e11;
      out_K_sf(8, 6) = -.5760000000e11;
      out_K_sf(9, 6) = 3200000000.;
      out_K_sf(12, 6) = .2880000000e11;
      out_K_sf(13, 6) = .5760000000e11;
      out_K_sf(14, 6) = 3200000000.;
      out_K_sf(2, 8) = -500000.;
      out_K_sf(6, 8) = -2303808000.;
      out_K_sf(6, 9) = -.1920000000e11;
      out_K_sf(6, 10) = -666666.6667;
      out_K_sf(10, 10) = -666666.6667;
      out_K_sf(11, 11) = -.2222222225e11;
      out_K_sf(7, 12) = -.8888888888e11;
      out_K_sf(9, 12) = .1333333333e12;
      out_K_sf(12, 12) = -.8888888888e11;
      out_K_sf(14, 12) = -.1333333333e12;
      out_K_sf(8, 13) = -.6666666667e11;
      out_K_sf(13, 13) = -.6666666667e11;
      out_K_sf(7, 14) = -.1333333333e12;
      out_K_sf(9, 14) = .1333333333e12;
      out_K_sf(12, 14) = .1333333333e12;
      out_K_sf(14, 14) = .1333333333e12;
      out_K_sf(11, 15) = -.6666666667e11;
    end % K_sf
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_ss = K_ss( ~, ~, ~ )
      % Evaluate the stiffness matrix K_ss.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_ss = sparse(15, 15);
      out_K_ss(1, 1) = 666666.6667;
      out_K_ss(2, 2) = .2222272225e11;
      out_K_ss(3, 3) = .1263888889e12;
      out_K_ss(4, 3) = -.7500000000e11;
      out_K_ss(5, 3) = -.1333333333e12;
      out_K_ss(7, 3) = -.3750000000e11;
      out_K_ss(8, 3) = -.7500000000e11;
      out_K_ss(3, 4) = -.7500000000e11;
      out_K_ss(4, 4) = .2666666667e12;
      out_K_ss(7, 4) = .7500000000e11;
      out_K_ss(8, 4) = .1000000000e12;
      out_K_ss(3, 5) = -.1333333333e12;
      out_K_ss(5, 5) = .3166666667e12;
      out_K_ss(9, 5) = -.5000000000e11;
      out_K_ss(6, 6) = 3072810667.;
      out_K_ss(3, 7) = -.3750000000e11;
      out_K_ss(4, 7) = .7500000000e11;
      out_K_ss(7, 7) = .1455888889e12;
      out_K_ss(8, 7) = .1134000000e12;
      out_K_ss(9, 7) = -.1621333333e12;
      out_K_ss(3, 8) = -.7500000000e11;
      out_K_ss(4, 8) = .1000000000e12;
      out_K_ss(7, 8) = .1134000000e12;
      out_K_ss(8, 8) = .3834666667e12;
      out_K_ss(9, 8) = -.5760000000e11;
      out_K_ss(5, 9) = -.5000000000e11;
      out_K_ss(7, 9) = -.1621333333e12;
      out_K_ss(8, 9) = -.5760000000e11;
      out_K_ss(9, 9) = .3998666667e12;
      out_K_ss(10, 10) = 810666.6667;
      out_K_ss(11, 10) = -192000.;
      out_K_ss(10, 11) = -192000.;
      out_K_ss(11, 11) = .2222247825e11;
      out_K_ss(12, 12) = .1080888889e12;
      out_K_ss(13, 12) = .3840000000e11;
      out_K_ss(14, 12) = .1621333333e12;
      out_K_ss(12, 13) = .3840000000e11;
      out_K_ss(13, 13) = .1834666667e12;
      out_K_ss(14, 13) = .5760000000e11;
      out_K_ss(12, 14) = .1621333333e12;
      out_K_ss(13, 14) = .5760000000e11;
      out_K_ss(14, 14) = .3498666667e12;
    end % K_ss
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d = d( ~, ~, ~ )
      % Evaluate the deformation vector d.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d = sparse(30, 1);
      out_d(6) = -.00437677311130356;
      out_d(7) = .0130482631550507;
      out_d(8) = -.0131303193398193;
      out_d(12) = -.00326206578876522;
      out_d(14) = -.00826420763525479;
      out_d(18) = -.0026718661090044;
      out_d(19) = -1.01858103335904e-014;
      out_d(20) = -.016280185046482;
      out_d(24) = .00542672834638531;
    end % d
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d_f = d_f( ~, ~, ~ )
      % Evaluate the deformation vector d_f.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d_f = zeros(15, 1);
      out_d_f(1) = -.00437677311130356;
      out_d_f(2) = .0130482631550507;
      out_d_f(3) = -.0131303193398193;
      out_d_f(7) = -.00326206578876522;
      out_d_f(8) = -.00826420763525479;
      out_d_f(9) = -.0026718661090044;
      out_d_f(10) = -1.01858103335904e-014;
      out_d_f(11) = -.016280185046482;
      out_d_f(15) = .00542672834638531;
    end % d_f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d_s = d_s( ~, ~, ~ )
      % Evaluate the deformation vector d_s.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d_s = sparse(15, 1);
    end % d_s
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f = f( ~, ~, ~ )
      % Evaluate the force vector f.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f = sparse(30, 1);
      out_f(1) = -8698.84210380206;
      out_f(2) = 4132.5852626509;
      out_f(7) = 10000;
      out_f(13) = 3098.85680511483;
      out_f(20) = -10000;
      out_f(25) = -4399.97120756582;
      out_f(26) = 5867.22521686309;
    end % f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_f = f_f( ~, ~, ~ )
      % Evaluate the force vector f_f.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_f = sparse(15, 1);
      out_f_f(2) = 10000;
      out_f_f(11) = -10000;
    end % f_f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_s = f_s( ~, ~, ~ )
      % Evaluate the force vector f_s.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_s = sparse(15, 1);
      out_f_s(1) = -8698.84210380206;
      out_f_s(2) = 4132.5852626509;
      out_f_s(6) = 3098.85680511483;
      out_f_s(10) = -4399.97120756582;
      out_f_s(11) = 5867.22521686309;
    end % f_s
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_r = f_r( ~, ~, ~ )
      % Evaluate the force vector f_r.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_r = sparse(15, 1);
    end % f_r
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_perm = perm( ~ )
      % Evaluate the permutation vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_perm = zeros(30, 1);
      out_perm(1) = 6;
      out_perm(2) = 7;
      out_perm(3) = 8;
      out_perm(4) = 9;
      out_perm(5) = 10;
      out_perm(6) = 11;
      out_perm(7) = 12;
      out_perm(8) = 14;
      out_perm(9) = 18;
      out_perm(10) = 19;
      out_perm(11) = 20;
      out_perm(12) = 21;
      out_perm(13) = 22;
      out_perm(14) = 23;
      out_perm(15) = 24;
      out_perm(16) = 1;
      out_perm(17) = 2;
      out_perm(18) = 3;
      out_perm(19) = 4;
      out_perm(20) = 5;
      out_perm(21) = 13;
      out_perm(22) = 15;
      out_perm(23) = 16;
      out_perm(24) = 17;
      out_perm(25) = 25;
      out_perm(26) = 26;
      out_perm(27) = 27;
      out_perm(28) = 28;
      out_perm(29) = 29;
      out_perm(30) = 30;
    end % perm
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_unperm = unperm( ~ )
      % Evaluate the unpermutation vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_unperm = zeros(30, 1);
      out_unperm(1) = 16;
      out_unperm(2) = 17;
      out_unperm(3) = 18;
      out_unperm(4) = 19;
      out_unperm(5) = 20;
      out_unperm(6) = 1;
      out_unperm(7) = 2;
      out_unperm(8) = 3;
      out_unperm(9) = 4;
      out_unperm(10) = 5;
      out_unperm(11) = 6;
      out_unperm(12) = 7;
      out_unperm(13) = 21;
      out_unperm(14) = 8;
      out_unperm(15) = 22;
      out_unperm(16) = 23;
      out_unperm(17) = 24;
      out_unperm(18) = 9;
      out_unperm(19) = 10;
      out_unperm(20) = 11;
      out_unperm(21) = 12;
      out_unperm(22) = 13;
      out_unperm(23) = 14;
      out_unperm(24) = 15;
      out_unperm(25) = 25;
      out_unperm(26) = 26;
      out_unperm(27) = 27;
      out_unperm(28) = 28;
      out_unperm(29) = 29;
      out_unperm(30) = 30;
    end % unperm
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( ~, ~ )
      % Evaluate the veiling vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_v = zeros(0, 1);
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % Test_00

% That's All Folks!
