% +--------------------------------------------------------------------------+
% | 'TrussMe' module version 0.0 - BSD 3-Clause License - Copyright (c) 2023 |
% | Current version authors:                                                 |
% |   Davide Stocco and Matteo Larcher.                                      |
% +--------------------------------------------------------------------------+

% Matlab generated code for system: Test_10
% This file has been automatically generated by TrussMe.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef Test_10 < TrussMe.System
  %
  % Test_10 class
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = Test_10( varargin )
      % Class constructor.

      % User data
      if (nargin == 0)
        data.E = .2e12;
        data.G = .1e12;
        data.A = .1e-2;
        data.I__x = .2e-4;
        data.I__y = .1e-4;
        data.I__z = .1e-4;
        data.K = .1e5;
        data.T = .1e5;
        data.l = 1;
        data.F__x = .1e3;
        data.F__y = 0.;
        data.F__z = 0.;
        data.M__x = 0.;
        data.M__y = 0.;
        data.M__z = 0.;
      elseif (nargin == 1 && isstruct(varargin{1}))
        data = varargin{1};
      elseif (nargin == 15)
        data.E = varargin{1};
        data.G = varargin{2};
        data.A = varargin{3};
        data.I__x = varargin{4};
        data.I__y = varargin{5};
        data.I__z = varargin{6};
        data.K = varargin{7};
        data.T = varargin{8};
        data.l = varargin{9};
        data.F__x = varargin{10};
        data.F__y = varargin{11};
        data.F__z = varargin{12};
        data.M__x = varargin{13};
        data.M__y = varargin{14};
        data.M__z = varargin{15};
      else
        error('wrong number of input arguments.');
      end

      % Call superclass constructor
      this = this@TrussMe.System(data);
    end % Test_10
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K = K( this, ~, ~ )
      % Evaluate the stiffness matrix K.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;

      % Extract inputs
      % No inputs

      % Evaluate function
      out_1_1 = K;
      out_7_1 = -K;
      out_2_2 = K;
      out_8_2 = out_7_1;
      out_3_3 = K;
      out_9_3 = out_8_2;
      out_4_4 = T;
      out_10_4 = -T;
      out_5_5 = T;
      out_11_5 = out_10_4;
      out_6_6 = T;
      out_12_6 = out_11_5;
      out_1_7 = out_9_3;
      t2 = l ^ 2;
      t4 = t2 * l;
      t5 = t4 * K;
      t7 = E * I__z;
      t10 = 0.1e1 / t4;
      out_7_7 = t10 * (t2 * E * A + 2 * t5 + 12 * t7) / 2;
      t12 = t2 * A;
      t13 = 12 * I__z;
      out_8_7 = t10 * (t12 - t13) * E / 2;
      t17 = sqrt(2);
      t18 = E * t17;
      t19 = 0.1e1 / t2;
      t21 = t19 * I__z * t18;
      t22 = 3 * t21;
      out_12_7 = -t22;
      out_13_7 = -t10 * (t12 + t13) * E / 2;
      out_14_7 = -out_8_7;
      out_18_7 = out_12_7;
      out_2_8 = out_1_7;
      out_7_8 = out_8_7;
      out_8_8 = out_7_7;
      out_12_8 = t22;
      out_13_8 = out_14_7;
      out_14_8 = out_13_7;
      out_18_8 = out_12_8;
      out_3_9 = out_2_8;
      t27 = E * I__y;
      out_9_9 = t10 * (t5 + 12 * t27);
      t31 = t19 * I__y * t18;
      out_10_9 = 3 * t31;
      out_11_9 = -out_10_9;
      t32 = t10 * t27;
      t33 = 12 * t32;
      out_15_9 = -t33;
      out_16_9 = out_10_9;
      out_17_9 = out_11_9;
      out_4_10 = out_12_6;
      out_9_10 = out_16_9;
      t34 = 4 * t27;
      t35 = G * I__x;
      t36 = T * l;
      t39 = 0.1e1 / l;
      out_10_10 = t39 * (t34 + t35 + 2 * t36) / 2;
      t41 = -t34 + t35;
      out_11_10 = t39 * t41 / 2;
      out_15_10 = out_17_9;
      t43 = 2 * t27;
      out_16_10 = t39 * (t43 - t35) / 2;
      t46 = -t43 - t35;
      out_17_10 = t39 * t46 / 2;
      out_5_11 = out_4_10;
      out_9_11 = out_15_10;
      out_10_11 = out_11_10;
      out_11_11 = out_10_10;
      out_15_11 = out_9_10;
      out_16_11 = out_17_10;
      out_17_11 = out_16_10;
      out_6_12 = out_5_11;
      out_7_12 = out_18_7;
      out_8_12 = out_18_8;
      out_12_12 = t39 * (4 * t7 + t36);
      out_13_12 = out_8_12;
      out_14_12 = out_7_12;
      t50 = t39 * t7;
      out_18_12 = 2 * t50;
      out_7_13 = out_14_8;
      out_8_13 = out_13_8;
      out_12_13 = out_13_12;
      out_13_13 = t10 * (2 * t12 + 15 * I__z) * E / 2;
      out_14_13 = -0.9e1 / 0.2e1 * t10 * t7;
      out_18_13 = out_12_13;
      t58 = 3 * I__z;
      t62 = t10 * (t12 + t58) * E / 2;
      out_19_13 = -t62;
      out_20_13 = t10 * (t12 - t58) * E / 2;
      out_24_13 = 0.3e1 / 0.2e1 * t21;
      out_7_14 = out_8_13;
      out_8_14 = out_7_13;
      out_12_14 = out_14_12;
      out_13_14 = out_14_13;
      out_14_14 = out_13_13;
      out_18_14 = out_12_14;
      out_19_14 = out_20_13;
      out_20_14 = out_19_13;
      out_24_14 = out_24_13;
      out_9_15 = out_15_9;
      out_10_15 = out_9_11;
      out_11_15 = out_15_11;
      out_15_15 = 24 * t32;
      out_16_15 = -6 * t31;
      out_21_15 = out_9_15;
      out_22_15 = out_10_15;
      out_23_15 = out_22_15;
      out_9_16 = out_11_15;
      out_10_16 = out_17_11;
      out_11_16 = out_16_11;
      out_15_16 = out_16_15;
      out_16_16 = t39 * (t34 + t35);
      out_21_16 = out_9_16;
      out_22_16 = out_10_16;
      out_23_16 = -t39 * t46 / 2;
      out_9_17 = out_23_15;
      out_10_17 = out_11_16;
      out_11_17 = out_22_16;
      out_17_17 = out_16_16;
      out_21_17 = out_21_16;
      out_22_17 = out_23_16;
      out_23_17 = out_11_17;
      out_7_18 = out_18_14;
      out_8_18 = out_18_13;
      out_12_18 = out_18_12;
      out_13_18 = out_8_18;
      out_14_18 = out_7_18;
      out_18_18 = 4 * t50;
      out_13_19 = out_20_14;
      out_14_19 = out_19_14;
      out_19_19 = t62;
      out_20_19 = -out_14_19;
      out_24_19 = -out_24_14;
      out_13_20 = out_14_19;
      out_14_20 = out_13_19;
      out_19_20 = out_20_19;
      out_20_20 = out_19_19;
      out_24_20 = out_24_19;
      out_15_21 = out_21_15;
      out_16_21 = out_21_17;
      out_17_21 = out_16_21;
      out_21_21 = t33;
      out_22_21 = out_17_21;
      out_23_21 = out_22_21;
      out_15_22 = out_9_17;
      out_16_22 = out_23_17;
      out_17_22 = out_22_17;
      out_21_22 = out_23_21;
      out_22_22 = out_17_17 / 2;
      out_23_22 = -t39 * t41 / 2;
      out_15_23 = out_15_22;
      out_16_23 = out_17_22;
      out_17_23 = out_16_22;
      out_21_23 = out_21_22;
      out_22_23 = out_23_22;
      out_23_23 = out_22_22;
      out_13_24 = out_24_14;
      out_14_24 = out_13_24;
      out_19_24 = out_24_20;
      out_20_24 = out_19_24;
      out_24_24 = 3 * t50;

      % Store outputs
      out_K = sparse(24, 24);
      out_K(1, 1) = out_1_1;
      out_K(7, 1) = out_7_1;
      out_K(2, 2) = out_2_2;
      out_K(8, 2) = out_8_2;
      out_K(3, 3) = out_3_3;
      out_K(9, 3) = out_9_3;
      out_K(4, 4) = out_4_4;
      out_K(10, 4) = out_10_4;
      out_K(5, 5) = out_5_5;
      out_K(11, 5) = out_11_5;
      out_K(6, 6) = out_6_6;
      out_K(12, 6) = out_12_6;
      out_K(1, 7) = out_1_7;
      out_K(7, 7) = out_7_7;
      out_K(8, 7) = out_8_7;
      out_K(12, 7) = out_12_7;
      out_K(13, 7) = out_13_7;
      out_K(14, 7) = out_14_7;
      out_K(18, 7) = out_18_7;
      out_K(2, 8) = out_2_8;
      out_K(7, 8) = out_7_8;
      out_K(8, 8) = out_8_8;
      out_K(12, 8) = out_12_8;
      out_K(13, 8) = out_13_8;
      out_K(14, 8) = out_14_8;
      out_K(18, 8) = out_18_8;
      out_K(3, 9) = out_3_9;
      out_K(9, 9) = out_9_9;
      out_K(10, 9) = out_10_9;
      out_K(11, 9) = out_11_9;
      out_K(15, 9) = out_15_9;
      out_K(16, 9) = out_16_9;
      out_K(17, 9) = out_17_9;
      out_K(4, 10) = out_4_10;
      out_K(9, 10) = out_9_10;
      out_K(10, 10) = out_10_10;
      out_K(11, 10) = out_11_10;
      out_K(15, 10) = out_15_10;
      out_K(16, 10) = out_16_10;
      out_K(17, 10) = out_17_10;
      out_K(5, 11) = out_5_11;
      out_K(9, 11) = out_9_11;
      out_K(10, 11) = out_10_11;
      out_K(11, 11) = out_11_11;
      out_K(15, 11) = out_15_11;
      out_K(16, 11) = out_16_11;
      out_K(17, 11) = out_17_11;
      out_K(6, 12) = out_6_12;
      out_K(7, 12) = out_7_12;
      out_K(8, 12) = out_8_12;
      out_K(12, 12) = out_12_12;
      out_K(13, 12) = out_13_12;
      out_K(14, 12) = out_14_12;
      out_K(18, 12) = out_18_12;
      out_K(7, 13) = out_7_13;
      out_K(8, 13) = out_8_13;
      out_K(12, 13) = out_12_13;
      out_K(13, 13) = out_13_13;
      out_K(14, 13) = out_14_13;
      out_K(18, 13) = out_18_13;
      out_K(19, 13) = out_19_13;
      out_K(20, 13) = out_20_13;
      out_K(24, 13) = out_24_13;
      out_K(7, 14) = out_7_14;
      out_K(8, 14) = out_8_14;
      out_K(12, 14) = out_12_14;
      out_K(13, 14) = out_13_14;
      out_K(14, 14) = out_14_14;
      out_K(18, 14) = out_18_14;
      out_K(19, 14) = out_19_14;
      out_K(20, 14) = out_20_14;
      out_K(24, 14) = out_24_14;
      out_K(9, 15) = out_9_15;
      out_K(10, 15) = out_10_15;
      out_K(11, 15) = out_11_15;
      out_K(15, 15) = out_15_15;
      out_K(16, 15) = out_16_15;
      out_K(21, 15) = out_21_15;
      out_K(22, 15) = out_22_15;
      out_K(23, 15) = out_23_15;
      out_K(9, 16) = out_9_16;
      out_K(10, 16) = out_10_16;
      out_K(11, 16) = out_11_16;
      out_K(15, 16) = out_15_16;
      out_K(16, 16) = out_16_16;
      out_K(21, 16) = out_21_16;
      out_K(22, 16) = out_22_16;
      out_K(23, 16) = out_23_16;
      out_K(9, 17) = out_9_17;
      out_K(10, 17) = out_10_17;
      out_K(11, 17) = out_11_17;
      out_K(17, 17) = out_17_17;
      out_K(21, 17) = out_21_17;
      out_K(22, 17) = out_22_17;
      out_K(23, 17) = out_23_17;
      out_K(7, 18) = out_7_18;
      out_K(8, 18) = out_8_18;
      out_K(12, 18) = out_12_18;
      out_K(13, 18) = out_13_18;
      out_K(14, 18) = out_14_18;
      out_K(18, 18) = out_18_18;
      out_K(13, 19) = out_13_19;
      out_K(14, 19) = out_14_19;
      out_K(19, 19) = out_19_19;
      out_K(20, 19) = out_20_19;
      out_K(24, 19) = out_24_19;
      out_K(13, 20) = out_13_20;
      out_K(14, 20) = out_14_20;
      out_K(19, 20) = out_19_20;
      out_K(20, 20) = out_20_20;
      out_K(24, 20) = out_24_20;
      out_K(15, 21) = out_15_21;
      out_K(16, 21) = out_16_21;
      out_K(17, 21) = out_17_21;
      out_K(21, 21) = out_21_21;
      out_K(22, 21) = out_22_21;
      out_K(23, 21) = out_23_21;
      out_K(15, 22) = out_15_22;
      out_K(16, 22) = out_16_22;
      out_K(17, 22) = out_17_22;
      out_K(21, 22) = out_21_22;
      out_K(22, 22) = out_22_22;
      out_K(23, 22) = out_23_22;
      out_K(15, 23) = out_15_23;
      out_K(16, 23) = out_16_23;
      out_K(17, 23) = out_17_23;
      out_K(21, 23) = out_21_23;
      out_K(22, 23) = out_22_23;
      out_K(23, 23) = out_23_23;
      out_K(13, 24) = out_13_24;
      out_K(14, 24) = out_14_24;
      out_K(19, 24) = out_19_24;
      out_K(20, 24) = out_20_24;
      out_K(24, 24) = out_24_24;
    end % K
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_ff = K_ff( this, ~, ~ )
      % Evaluate the stiffness matrix K_ff.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;

      % Extract inputs
      % No inputs

      % Evaluate function
      out_1_1 = T;
      out_7_1 = -T;
      t2 = l ^ 2;
      t4 = t2 * l;
      t5 = t4 * K;
      t7 = E * I__z;
      t10 = 0.1e1 / t4;
      out_2_2 = t10 * (t2 * E * A + 2 * t5 + 12 * t7) / 2;
      t12 = t2 * A;
      t13 = 12 * I__z;
      out_3_2 = t10 * (t12 - t13) * E / 2;
      t17 = sqrt(2);
      t18 = E * t17;
      t19 = 0.1e1 / t2;
      t21 = t19 * I__z * t18;
      t22 = 3 * t21;
      out_7_2 = -t22;
      out_8_2 = -t10 * (t12 + t13) * E / 2;
      out_9_2 = -out_3_2;
      out_13_2 = out_7_2;
      out_2_3 = out_3_2;
      out_3_3 = out_2_2;
      out_7_3 = t22;
      out_8_3 = out_9_2;
      out_9_3 = out_8_2;
      out_13_3 = out_7_3;
      t27 = E * I__y;
      out_4_4 = t10 * (t5 + 12 * t27);
      t31 = t19 * I__y * t18;
      out_5_4 = 3 * t31;
      out_6_4 = -out_5_4;
      t32 = t10 * t27;
      out_10_4 = -12 * t32;
      out_11_4 = out_5_4;
      out_12_4 = out_6_4;
      out_4_5 = out_11_4;
      t34 = 4 * t27;
      t35 = G * I__x;
      t36 = T * l;
      t39 = 0.1e1 / l;
      out_5_5 = t39 * (t34 + t35 + 2 * t36) / 2;
      out_6_5 = t39 * (-t34 + t35) / 2;
      out_10_5 = out_12_4;
      t43 = 2 * t27;
      out_11_5 = t39 * (t43 - t35) / 2;
      out_12_5 = t39 * (-t43 - t35) / 2;
      out_4_6 = out_10_5;
      out_5_6 = out_6_5;
      out_6_6 = out_5_5;
      out_10_6 = out_4_5;
      out_11_6 = out_12_5;
      out_12_6 = out_11_5;
      out_1_7 = out_7_1;
      out_2_7 = out_13_2;
      out_3_7 = out_13_3;
      out_7_7 = t39 * (4 * t7 + t36);
      out_8_7 = out_3_7;
      out_9_7 = out_2_7;
      t50 = t39 * t7;
      out_13_7 = 2 * t50;
      out_2_8 = out_9_3;
      out_3_8 = out_8_3;
      out_7_8 = out_8_7;
      out_8_8 = t10 * (2 * t12 + 15 * I__z) * E / 2;
      out_9_8 = -0.9e1 / 0.2e1 * t10 * t7;
      out_13_8 = out_7_8;
      out_14_8 = 0.3e1 / 0.2e1 * t21;
      out_2_9 = out_3_8;
      out_3_9 = out_2_8;
      out_7_9 = out_9_7;
      out_8_9 = out_9_8;
      out_9_9 = out_8_8;
      out_13_9 = out_7_9;
      out_14_9 = out_14_8;
      out_4_10 = out_10_4;
      out_5_10 = out_4_6;
      out_6_10 = out_10_6;
      out_10_10 = 24 * t32;
      out_11_10 = -6 * t31;
      out_4_11 = out_6_10;
      out_5_11 = out_12_6;
      out_6_11 = out_11_6;
      out_10_11 = out_11_10;
      out_11_11 = t39 * (t34 + t35);
      out_4_12 = out_5_10;
      out_5_12 = out_6_11;
      out_6_12 = out_5_11;
      out_12_12 = out_11_11;
      out_2_13 = out_13_9;
      out_3_13 = out_13_8;
      out_7_13 = out_13_7;
      out_8_13 = out_3_13;
      out_9_13 = out_2_13;
      out_13_13 = 4 * t50;
      out_8_14 = out_14_9;
      out_9_14 = out_8_14;
      out_14_14 = 3 * t50;

      % Store outputs
      out_K_ff = sparse(14, 14);
      out_K_ff(1, 1) = out_1_1;
      out_K_ff(7, 1) = out_7_1;
      out_K_ff(2, 2) = out_2_2;
      out_K_ff(3, 2) = out_3_2;
      out_K_ff(7, 2) = out_7_2;
      out_K_ff(8, 2) = out_8_2;
      out_K_ff(9, 2) = out_9_2;
      out_K_ff(13, 2) = out_13_2;
      out_K_ff(2, 3) = out_2_3;
      out_K_ff(3, 3) = out_3_3;
      out_K_ff(7, 3) = out_7_3;
      out_K_ff(8, 3) = out_8_3;
      out_K_ff(9, 3) = out_9_3;
      out_K_ff(13, 3) = out_13_3;
      out_K_ff(4, 4) = out_4_4;
      out_K_ff(5, 4) = out_5_4;
      out_K_ff(6, 4) = out_6_4;
      out_K_ff(10, 4) = out_10_4;
      out_K_ff(11, 4) = out_11_4;
      out_K_ff(12, 4) = out_12_4;
      out_K_ff(4, 5) = out_4_5;
      out_K_ff(5, 5) = out_5_5;
      out_K_ff(6, 5) = out_6_5;
      out_K_ff(10, 5) = out_10_5;
      out_K_ff(11, 5) = out_11_5;
      out_K_ff(12, 5) = out_12_5;
      out_K_ff(4, 6) = out_4_6;
      out_K_ff(5, 6) = out_5_6;
      out_K_ff(6, 6) = out_6_6;
      out_K_ff(10, 6) = out_10_6;
      out_K_ff(11, 6) = out_11_6;
      out_K_ff(12, 6) = out_12_6;
      out_K_ff(1, 7) = out_1_7;
      out_K_ff(2, 7) = out_2_7;
      out_K_ff(3, 7) = out_3_7;
      out_K_ff(7, 7) = out_7_7;
      out_K_ff(8, 7) = out_8_7;
      out_K_ff(9, 7) = out_9_7;
      out_K_ff(13, 7) = out_13_7;
      out_K_ff(2, 8) = out_2_8;
      out_K_ff(3, 8) = out_3_8;
      out_K_ff(7, 8) = out_7_8;
      out_K_ff(8, 8) = out_8_8;
      out_K_ff(9, 8) = out_9_8;
      out_K_ff(13, 8) = out_13_8;
      out_K_ff(14, 8) = out_14_8;
      out_K_ff(2, 9) = out_2_9;
      out_K_ff(3, 9) = out_3_9;
      out_K_ff(7, 9) = out_7_9;
      out_K_ff(8, 9) = out_8_9;
      out_K_ff(9, 9) = out_9_9;
      out_K_ff(13, 9) = out_13_9;
      out_K_ff(14, 9) = out_14_9;
      out_K_ff(4, 10) = out_4_10;
      out_K_ff(5, 10) = out_5_10;
      out_K_ff(6, 10) = out_6_10;
      out_K_ff(10, 10) = out_10_10;
      out_K_ff(11, 10) = out_11_10;
      out_K_ff(4, 11) = out_4_11;
      out_K_ff(5, 11) = out_5_11;
      out_K_ff(6, 11) = out_6_11;
      out_K_ff(10, 11) = out_10_11;
      out_K_ff(11, 11) = out_11_11;
      out_K_ff(4, 12) = out_4_12;
      out_K_ff(5, 12) = out_5_12;
      out_K_ff(6, 12) = out_6_12;
      out_K_ff(12, 12) = out_12_12;
      out_K_ff(2, 13) = out_2_13;
      out_K_ff(3, 13) = out_3_13;
      out_K_ff(7, 13) = out_7_13;
      out_K_ff(8, 13) = out_8_13;
      out_K_ff(9, 13) = out_9_13;
      out_K_ff(13, 13) = out_13_13;
      out_K_ff(8, 14) = out_8_14;
      out_K_ff(9, 14) = out_9_14;
      out_K_ff(14, 14) = out_14_14;
    end % K_ff
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_fs = K_fs( this, ~, ~ )
      % Evaluate the stiffness matrix K_fs.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;

      % Extract inputs
      % No inputs

      % Evaluate function
      out_2_1 = -K;
      out_3_2 = out_2_1;
      out_4_3 = out_3_2;
      out_5_4 = -T;
      out_6_5 = out_5_4;
      t1 = l ^ 2;
      t2 = t1 * A;
      t3 = 3 * I__z;
      t7 = 0.1e1 / t1 / l;
      out_8_6 = -t7 * (t2 + t3) * E / 2;
      out_9_6 = t7 * (t2 - t3) * E / 2;
      t13 = sqrt(2);
      t14 = E * t13;
      t15 = 0.1e1 / t1;
      out_14_6 = -0.3e1 / 0.2e1 * t15 * I__z * t14;
      out_8_7 = out_9_6;
      out_9_7 = out_8_6;
      out_14_7 = out_14_6;
      t19 = E * I__y;
      out_10_8 = -12 * t7 * t19;
      out_11_8 = 3 * t15 * I__y * t14;
      out_12_8 = out_11_8;
      out_10_9 = -out_12_8;
      t24 = 2 * t19;
      t25 = G * I__x;
      t27 = 0.1e1 / l;
      out_11_9 = t27 * (t24 - t25) / 2;
      out_12_9 = t27 * (t24 + t25) / 2;
      out_10_10 = out_10_9;
      out_11_10 = out_12_9;
      out_12_10 = out_11_9;

      % Store outputs
      out_K_fs = sparse(14, 10);
      out_K_fs(2, 1) = out_2_1;
      out_K_fs(3, 2) = out_3_2;
      out_K_fs(4, 3) = out_4_3;
      out_K_fs(5, 4) = out_5_4;
      out_K_fs(6, 5) = out_6_5;
      out_K_fs(8, 6) = out_8_6;
      out_K_fs(9, 6) = out_9_6;
      out_K_fs(14, 6) = out_14_6;
      out_K_fs(8, 7) = out_8_7;
      out_K_fs(9, 7) = out_9_7;
      out_K_fs(14, 7) = out_14_7;
      out_K_fs(10, 8) = out_10_8;
      out_K_fs(11, 8) = out_11_8;
      out_K_fs(12, 8) = out_12_8;
      out_K_fs(10, 9) = out_10_9;
      out_K_fs(11, 9) = out_11_9;
      out_K_fs(12, 9) = out_12_9;
      out_K_fs(10, 10) = out_10_10;
      out_K_fs(11, 10) = out_11_10;
      out_K_fs(12, 10) = out_12_10;
    end % K_fs
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_sf = K_sf( this, ~, ~ )
      % Evaluate the stiffness matrix K_sf.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;

      % Extract inputs
      % No inputs

      % Evaluate function
      out_1_2 = -K;
      out_2_3 = out_1_2;
      out_3_4 = out_2_3;
      out_4_5 = -T;
      out_5_6 = out_4_5;
      t1 = l ^ 2;
      t2 = t1 * A;
      t3 = 3 * I__z;
      t7 = 0.1e1 / t1 / l;
      out_6_8 = -t7 * (t2 + t3) * E / 2;
      out_7_8 = t7 * (t2 - t3) * E / 2;
      out_6_9 = out_7_8;
      out_7_9 = out_6_8;
      t13 = E * I__y;
      out_8_10 = -12 * t7 * t13;
      t16 = sqrt(2);
      t17 = E * t16;
      t18 = 0.1e1 / t1;
      t21 = 3 * t18 * I__y * t17;
      out_9_10 = -t21;
      out_10_10 = out_9_10;
      out_8_11 = t21;
      t22 = 2 * t13;
      t23 = G * I__x;
      t25 = 0.1e1 / l;
      out_9_11 = t25 * (t22 - t23) / 2;
      out_10_11 = t25 * (t22 + t23) / 2;
      out_8_12 = out_8_11;
      out_9_12 = out_10_11;
      out_10_12 = out_9_11;
      out_6_14 = -0.3e1 / 0.2e1 * t18 * I__z * t17;
      out_7_14 = out_6_14;

      % Store outputs
      out_K_sf = sparse(10, 14);
      out_K_sf(1, 2) = out_1_2;
      out_K_sf(2, 3) = out_2_3;
      out_K_sf(3, 4) = out_3_4;
      out_K_sf(4, 5) = out_4_5;
      out_K_sf(5, 6) = out_5_6;
      out_K_sf(6, 8) = out_6_8;
      out_K_sf(7, 8) = out_7_8;
      out_K_sf(6, 9) = out_6_9;
      out_K_sf(7, 9) = out_7_9;
      out_K_sf(8, 10) = out_8_10;
      out_K_sf(9, 10) = out_9_10;
      out_K_sf(10, 10) = out_10_10;
      out_K_sf(8, 11) = out_8_11;
      out_K_sf(9, 11) = out_9_11;
      out_K_sf(10, 11) = out_10_11;
      out_K_sf(8, 12) = out_8_12;
      out_K_sf(9, 12) = out_9_12;
      out_K_sf(10, 12) = out_10_12;
      out_K_sf(6, 14) = out_6_14;
      out_K_sf(7, 14) = out_7_14;
    end % K_sf
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_ss = K_ss( this, ~, ~ )
      % Evaluate the stiffness matrix K_ss.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;

      % Extract inputs
      % No inputs

      % Evaluate function
      out_1_1 = K;
      out_2_2 = K;
      out_3_3 = K;
      out_4_4 = T;
      out_5_5 = T;
      t1 = l ^ 2;
      t2 = t1 * A;
      t3 = 3 * I__z;
      t7 = 0.1e1 / t1 / l;
      out_6_6 = t7 * (t2 + t3) * E / 2;
      out_7_6 = -t7 * (t2 - t3) * E / 2;
      out_6_7 = out_7_6;
      out_7_7 = out_6_6;
      t13 = E * I__y;
      out_8_8 = 12 * t7 * t13;
      t15 = sqrt(2);
      out_9_8 = 3 / t1 * I__y * E * t15;
      out_10_8 = out_9_8;
      out_8_9 = out_10_8;
      t20 = 4 * t13;
      t21 = G * I__x;
      t23 = 0.1e1 / l;
      out_9_9 = t23 * (t20 + t21) / 2;
      out_10_9 = t23 * (t20 - t21) / 2;
      out_8_10 = out_8_9;
      out_9_10 = out_10_9;
      out_10_10 = out_9_9;

      % Store outputs
      out_K_ss = sparse(10, 10);
      out_K_ss(1, 1) = out_1_1;
      out_K_ss(2, 2) = out_2_2;
      out_K_ss(3, 3) = out_3_3;
      out_K_ss(4, 4) = out_4_4;
      out_K_ss(5, 5) = out_5_5;
      out_K_ss(6, 6) = out_6_6;
      out_K_ss(7, 6) = out_7_6;
      out_K_ss(6, 7) = out_6_7;
      out_K_ss(7, 7) = out_7_7;
      out_K_ss(8, 8) = out_8_8;
      out_K_ss(9, 8) = out_9_8;
      out_K_ss(10, 8) = out_10_8;
      out_K_ss(8, 9) = out_8_9;
      out_K_ss(9, 9) = out_9_9;
      out_K_ss(10, 9) = out_10_9;
      out_K_ss(8, 10) = out_8_10;
      out_K_ss(9, 10) = out_9_10;
      out_K_ss(10, 10) = out_10_10;
    end % K_ss
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d = d( this, ~, ~ )
      % Evaluate the deformation vector d.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;
      F__x = this.m_data.F__x;
      F__y = this.m_data.F__y;
      F__z = this.m_data.F__z;
      M__x = this.m_data.M__x;
      M__y = this.m_data.M__y;
      M__z = this.m_data.M__z;

      % Extract inputs
      % No inputs

      % Evaluate function
      t2 = l ^ 2;
      t3 = t2 * l;
      t5 = t3 * M__z * A * K;
      t7 = sqrt(2);
      t9 = t2 * t7 * K;
      t11 = 3 * t9 * F__x * I__z;
      t14 = 3 * t9 * F__y * I__z;
      t16 = A * E;
      t18 = 6 * t16 * I__z * M__z;
      t22 = 6 * I__z * K * M__z * l;
      t24 = 0.1e1 / t2;
      t26 = 0.1e1 / K;
      t28 = 0.1e1 / A;
      t29 = 0.1e1 / E;
      t30 = t29 * t28;
      t32 = 0.1e1 / I__z * t30;
      out_6 = t32 * t26 * t24 * (-t5 - t11 + t14 + t18 + t22) / 6;
      t34 = 0.1e1 / l;
      t36 = F__x * l;
      t37 = F__y * l;
      t38 = t7 * M__z;
      out_7 = (t36 + t37 + t38) * t34 * t26 / 2;
      out_8 = t34 * t26 * (t36 + t37 - t38) / 2;
      t44 = E ^ 2;
      t45 = I__y ^ 2;
      t46 = t45 * t44;
      t47 = t7 * M__x;
      t50 = t44 * t7;
      t51 = M__y * t45;
      t54 = F__z * E;
      t55 = G * t54;
      t56 = I__y * I__x;
      t60 = T * I__y;
      t64 = G * E;
      t65 = I__x * t64;
      t66 = M__x * I__y;
      t70 = E * t7;
      t76 = T * M__y;
      t77 = l * t76;
      t80 = F__z * G;
      t89 = K * I__y;
      t93 = E * I__y;
      t94 = T * K;
      t95 = t2 ^ 2;
      t96 = t95 * t94;
      t99 = G * I__x;
      t101 = G * t44;
      t102 = t45 * I__x;
      t103 = t102 * t101;
      t105 = T * l;
      t112 = 0.1e1 / (6 * t3 * K * t46 + 6 * l * t60 * t65 + 4 * t3 * t89 * t65 + 6 * t105 * t46 + 4 * t96 * t93 + t96 * t99 + 6 * t103);
      out_9 = t112 * t2 * (3 * M__y * t56 * G * t70 + t2 * T * I__x * t80 + 6 * t77 * I__y * t70 + 4 * l * t56 * t55 + 4 * t2 * t60 * t54 + 3 * t7 * t66 * t65 - 6 * t47 * t46 + 6 * t51 * t50) / 2;
      t114 = t80 * t70;
      t115 = t95 * l;
      t116 = t115 * t94;
      t118 = t116 * t56 * t114;
      t120 = G ^ 2;
      t121 = t120 * F__z;
      t122 = t121 * t70;
      t123 = I__x ^ 2;
      t124 = I__y * t123;
      t125 = t2 * T;
      t127 = t125 * t124 * t122;
      t128 = 6 * t127;
      t129 = t56 * t64;
      t130 = K * M__y;
      t131 = t95 * T;
      t133 = t131 * t130 * t129;
      t137 = M__x * T;
      t139 = t137 * t89 * t99 * E * t95;
      t141 = t80 * t50;
      t142 = t95 * K;
      t144 = t142 * t102 * t141;
      t148 = 4 * t142 * t124 * t122;
      t150 = t125 * t102 * t141;
      t151 = 6 * t150;
      t152 = F__z * t50;
      t153 = K * t45;
      t154 = t115 * T;
      t155 = t154 * t153;
      t157 = 4 * t155 * t152;
      t162 = t154 * K * t123 * t120 * F__z * t7;
      t163 = t123 * t120;
      t166 = l * t45 * t163 * t152;
      t167 = 6 * t166;
      t173 = I__x * t101;
      t174 = t3 * M__x;
      t176 = t174 * t153 * t173;
      t178 = t3 * M__y;
      t180 = t178 * t153 * t173;
      t182 = -24 * t137 * t102 * G * t44 * l - 5 * t118 - t128 - 6 * t133 - 10 * t139 - 10 * t144 - t148 - t151 - t157 - t162 - t167 - 26 * t176 - 10 * t180;
      t183 = K * t46;
      t184 = t95 * t137;
      t186 = 8 * t184 * t183;
      t187 = t95 * t76;
      t188 = t187 * t183;
      t189 = 4 * t188;
      t190 = t120 * E;
      t191 = t123 * t190;
      t193 = t174 * t89 * t191;
      t196 = t178 * t89 * t191;
      t198 = K * t163;
      t199 = t184 * t198;
      t200 = 2 * t199;
      t201 = t187 * t198;
      t202 = 2 * t201;
      t203 = t44 * E;
      t204 = G * t203;
      t205 = t45 * I__y;
      t206 = t205 * I__x;
      t208 = M__x * t206 * t204;
      t209 = 12 * t208;
      t211 = M__y * t206 * t204;
      t212 = 12 * t211;
      t213 = t205 * t203;
      t215 = l * t137 * t213;
      t216 = 12 * t215;
      t217 = t77 * t213;
      t218 = 12 * t217;
      t219 = t120 * t44;
      t220 = t45 * t123;
      t222 = M__x * t220 * t219;
      t223 = 12 * t222;
      t225 = M__y * t220 * t219;
      t226 = 12 * t225;
      t228 = t105 * t66 * t191;
      t229 = 12 * t228;
      t230 = I__y * M__y;
      t232 = t105 * t230 * t191;
      t233 = 12 * t232;
      t234 = -t186 - t189 - 8 * t193 - 8 * t196 - t200 - t202 - t209 + t212 - t216 + t218 - t223 - t226 - t229 - t233;
      t240 = 0.1e1 / (t105 * t93 + t105 * t99 + t129);
      t241 = t240 * t112;
      out_10 = -t241 * l * (t182 + t234) / 4;
      t251 = t118 - t128 + 2 * t133 - 6 * t139 - 2 * t144 - t151 + t157 - t167 - 10 * t176 - 2 * t180 - 2 * t193 - 2 * t196;
      t253 = t105 * t51 * t173;
      t255 = t186 + t189 - t200 - t202 + t209 - t212 + t216 - t218 - t223 - t226 - 24 * t253 - t229 - t233;
      out_11 = -t241 * l * (t251 + t255) / 4;
      out_12 = out_6;
      t264 = F__x * K;
      t265 = l * t7;
      t268 = K * M__z;
      out_13 = -t29 * t28 * t26 * (-t7 * F__x * t16 - t7 * F__y * t16 - 2 * t265 * t264 + 2 * t268) * t7 / 4;
      t276 = F__x * t16;
      t277 = F__y * t16;
      t279 = F__y * K * l;
      out_14 = t30 * t26 * (t7 * t268 + t276 + t277 + 2 * t279) / 2;
      t285 = T * t7;
      t286 = t95 * t285;
      t287 = t286 * t130;
      t290 = t124 * t190;
      t291 = K * M__x;
      t292 = t286 * t291;
      t297 = T ^ 2;
      t298 = t297 * t7;
      t305 = F__z * t44;
      t313 = t99 * t54;
      t314 = t95 * t2;
      t315 = t314 * t297;
      t319 = t206 * t204;
      t320 = t3 * t7;
      t321 = t320 * t291;
      t324 = t320 * t130;
      t327 = t220 * t219;
      t332 = t105 * t47;
      t335 = t7 * M__y;
      t336 = t105 * t335;
      t343 = t2 * t297;
      t350 = 6 * t115 * t298 * t291 * t129 + 8 * t154 * t89 * t163 * t54 + 36 * t343 * t335 * t103 + 36 * t343 * t47 * t103 + 44 * t155 * t99 * t305 + 8 * t315 * t89 * t313 + 6 * t287 * t103 + 42 * t292 * t103 + 3 * t287 * t290 + 3 * t292 * t290 + 60 * t321 * t319 + 12 * t324 * t319 + 72 * t332 * t319 + 72 * t336 * t319 + 12 * t321 * t327 + 12 * t324 * t327 + 36 * t332 * t327 + 36 * t336 * t327;
      t351 = F__z * t203;
      t352 = G * t351;
      t356 = t120 * t305;
      t366 = G * t305;
      t367 = t3 * t297;
      t371 = t120 * t54;
      t375 = K * t213;
      t382 = t115 * t297;
      t390 = t123 * t121;
      t391 = t297 * K;
      t392 = t314 * t391;
      t395 = t205 * t123;
      t399 = t120 * t203;
      t400 = t123 * t399;
      t401 = M__x * t205;
      t405 = M__y * t205;
      t409 = M__x * t213;
      t410 = t2 * t298;
      t413 = M__y * t213;
      t419 = t45 * t305;
      t422 = 48 * t142 * t206 * t352 + 16 * t142 * t220 * t356 + 96 * t125 * t206 * t352 + 60 * t125 * t220 * t356 + 60 * t367 * t102 * t366 + 12 * t367 * t124 * t371 + 60 * t131 * t47 * t375 + 12 * t131 * t335 * t375 + 24 * t382 * t47 * t183 + 48 * t3 * t297 * t205 * t351 + t392 * t390 + 48 * l * t395 * t120 * t351 + 36 * t7 * t401 * t400 + 36 * t7 * t405 * t400 + 36 * t410 * t409 + 36 * t410 * t413 + 48 * t116 * t205 * t351 + 16 * t392 * t419;
      out_15 = t240 * t112 / I__y * t29 * t2 * (t350 + t422) / 24;
      t430 = I__x * t204;
      t437 = t123 * t219;
      t444 = t115 * t391;
      t466 = t297 * t45;
      t474 = 6 * t2 * t297 * I__y * t191 + 6 * t3 * K * t205 * t430 + 12 * l * T * t205 * t430 + 12 * l * T * t45 * t437 + 14 * t131 * t153 * t173 + 5 * t131 * t89 * t191 + 4 * t3 * t153 * t437 + 12 * t2 * t466 * t173 + 5 * t382 * t89 * t65 + t444 * t163 + 6 * t343 * t213 + 6 * t96 * t213 + 6 * t395 * t399 + 4 * t444 * t46;
      t475 = 0.1e1 / t474;
      t485 = t125 * t47;
      t494 = t95 * t7;
      t495 = t494 * t291;
      t498 = t494 * t130;
      t510 = t115 * K;
      t517 = t3 * T;
      t528 = t154 * t47;
      t531 = 26 * t115 * t285 * t291 * t129 + 14 * t314 * T * t89 * t313 + 12 * t485 * t290 + 12 * t125 * t335 * t290 + 24 * t367 * t47 * t129 + 32 * t495 * t103 + 4 * t498 * t103 + 5 * t495 * t290 + 5 * t498 * t290 + 48 * t485 * t103 + 12 * t265 * t51 * t437 + 20 * t510 * t102 * t366 + 4 * t510 * t124 * t371 + 24 * t517 * t102 * t366 + 12 * t517 * t124 * t371 + 12 * t95 * t297 * t56 * t55 + 32 * t528 * t183;
      t532 = t154 * t335;
      t535 = K * t93;
      t536 = t315 * t47;
      t543 = K * t99;
      t559 = t2 * t285;
      t568 = t314 * t94;
      t573 = t95 * t3 * t391;
      t583 = 4 * t532 * t183 + 16 * t536 * t535 + 2 * t528 * t198 + 2 * t532 * t198 + 4 * t536 * t543 + 12 * t265 * t401 * t430 - 12 * t265 * t405 * t430 + 12 * t265 * M__x * t45 * t437 + 12 * t95 * t466 * t305 + 12 * t559 * t409 - 12 * t559 * t413 + 24 * t3 * t298 * M__x * t46 + 20 * t568 * t419 + 8 * t573 * I__y * t54 + t568 * t390 + 2 * t573 * I__x * t80 + 12 * t2 * t220 * t356;
      out_16 = (t531 + t583) * t7 * t475 / 8;
      t603 = -12 * t367 * t56 * t114 - 48 * t343 * t230 * t65 - 2 * t118 - 12 * t127 - 28 * t133 - 4 * t144 - t148 - 24 * t150 - t157 - t162 - 12 * t166 - 8 * t176 - 16 * t180 - 10 * t193 - 10 * t196 - 24 * t228;
      t606 = t297 * M__y;
      t619 = t115 * t606;
      t627 = -12 * t3 * t466 * t152 - 48 * t2 * t606 * t46 - 8 * t619 * t535 - 8 * t619 * t543 - t186 - 16 * t188 - 4 * t199 - 4 * t201 + 24 * t208 - 24 * t211 + 24 * t215 - 24 * t217 - 24 * t222 - 24 * t225 - 24 * t232 - 96 * t253;
      out_17 = -t475 * (t603 + t627) * l / 8;
      out_18 = t32 * t26 * t24 * (2 * t5 + t18 - t11 + t14 + t22) / 6;
      out_24 = -t34 * t30 * t26 * (l * t264 + t276 + t277 + t279) * t7 / 2;

      % Store outputs
      out_d = zeros(24, 1);
      out_d(6) = out_6;
      out_d(7) = out_7;
      out_d(8) = out_8;
      out_d(9) = out_9;
      out_d(10) = out_10;
      out_d(11) = out_11;
      out_d(12) = out_12;
      out_d(13) = out_13;
      out_d(14) = out_14;
      out_d(15) = out_15;
      out_d(16) = out_16;
      out_d(17) = out_17;
      out_d(18) = out_18;
      out_d(24) = out_24;
    end % d
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d_f = d_f( this, ~, ~ )
      % Evaluate the deformation vector d_f.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;
      F__x = this.m_data.F__x;
      F__y = this.m_data.F__y;
      F__z = this.m_data.F__z;
      M__x = this.m_data.M__x;
      M__y = this.m_data.M__y;
      M__z = this.m_data.M__z;

      % Extract inputs
      % No inputs

      % Evaluate function
      t2 = l ^ 2;
      t3 = t2 * l;
      t5 = t3 * M__z * A * K;
      t7 = sqrt(2);
      t9 = t2 * t7 * K;
      t11 = 3 * t9 * F__x * I__z;
      t14 = 3 * t9 * F__y * I__z;
      t16 = A * E;
      t18 = 6 * t16 * I__z * M__z;
      t22 = 6 * I__z * K * M__z * l;
      t24 = 0.1e1 / t2;
      t26 = 0.1e1 / K;
      t28 = 0.1e1 / A;
      t29 = 0.1e1 / E;
      t30 = t29 * t28;
      t32 = 0.1e1 / I__z * t30;
      out_1 = t32 * t26 * t24 * (-t5 - t11 + t14 + t18 + t22) / 6;
      t34 = 0.1e1 / l;
      t36 = F__x * l;
      t37 = F__y * l;
      t38 = t7 * M__z;
      out_2 = (t36 + t37 + t38) * t34 * t26 / 2;
      out_3 = t34 * t26 * (t36 + t37 - t38) / 2;
      t44 = E ^ 2;
      t45 = I__y ^ 2;
      t46 = t45 * t44;
      t47 = t7 * M__x;
      t50 = t44 * t7;
      t51 = M__y * t45;
      t54 = F__z * E;
      t55 = G * t54;
      t56 = I__y * I__x;
      t60 = T * I__y;
      t64 = G * E;
      t65 = I__x * t64;
      t66 = M__x * I__y;
      t70 = E * t7;
      t76 = T * M__y;
      t77 = l * t76;
      t80 = F__z * G;
      t89 = K * I__y;
      t93 = E * I__y;
      t94 = T * K;
      t95 = t2 ^ 2;
      t96 = t95 * t94;
      t99 = G * I__x;
      t101 = G * t44;
      t102 = t45 * I__x;
      t103 = t102 * t101;
      t105 = T * l;
      t112 = 0.1e1 / (6 * t3 * K * t46 + 6 * l * t60 * t65 + 4 * t3 * t89 * t65 + 6 * t105 * t46 + 4 * t96 * t93 + t96 * t99 + 6 * t103);
      out_4 = t112 * t2 * (3 * M__y * t56 * G * t70 + t2 * T * I__x * t80 + 6 * t77 * I__y * t70 + 4 * l * t56 * t55 + 4 * t2 * t60 * t54 + 3 * t7 * t66 * t65 - 6 * t47 * t46 + 6 * t51 * t50) / 2;
      t114 = K * t46;
      t115 = M__x * T;
      t116 = t95 * t115;
      t118 = 8 * t116 * t114;
      t119 = t95 * t76;
      t120 = t119 * t114;
      t121 = 4 * t120;
      t122 = G ^ 2;
      t123 = I__x ^ 2;
      t124 = t123 * t122;
      t125 = K * t124;
      t126 = t116 * t125;
      t127 = 2 * t126;
      t128 = t119 * t125;
      t129 = 2 * t128;
      t130 = t80 * t50;
      t131 = t2 * T;
      t133 = t131 * t102 * t130;
      t134 = 6 * t133;
      t135 = t122 * F__z;
      t136 = t135 * t70;
      t137 = I__y * t123;
      t139 = t131 * t137 * t136;
      t140 = 6 * t139;
      t141 = t56 * t64;
      t142 = K * M__y;
      t143 = t95 * T;
      t145 = t143 * t142 * t141;
      t150 = t115 * t89 * t99 * E * t95;
      t152 = t95 * K;
      t154 = t152 * t102 * t130;
      t158 = 4 * t152 * t137 * t136;
      t159 = t80 * t70;
      t160 = t95 * l;
      t161 = t160 * t94;
      t163 = t161 * t56 * t159;
      t165 = t44 * E;
      t166 = G * t165;
      t167 = t45 * I__y;
      t168 = t167 * I__x;
      t170 = M__x * t168 * t166;
      t171 = 12 * t170;
      t173 = M__y * t168 * t166;
      t174 = 12 * t173;
      t175 = -t118 - t121 - t127 - t129 - t134 - t140 - 6 * t145 - 10 * t150 - 10 * t154 - t158 - 5 * t163 - t171 + t174;
      t176 = t167 * t165;
      t178 = l * t115 * t176;
      t179 = 12 * t178;
      t180 = t77 * t176;
      t181 = 12 * t180;
      t182 = t122 * t44;
      t183 = t45 * t123;
      t185 = M__x * t183 * t182;
      t186 = 12 * t185;
      t188 = M__y * t183 * t182;
      t189 = 12 * t188;
      t190 = F__z * t50;
      t191 = K * t45;
      t192 = t160 * T;
      t193 = t192 * t191;
      t195 = 4 * t193 * t190;
      t200 = t192 * K * t123 * t122 * F__z * t7;
      t203 = l * t45 * t124 * t190;
      t204 = 6 * t203;
      t210 = I__x * t101;
      t211 = t3 * M__x;
      t213 = t211 * t191 * t210;
      t215 = t3 * M__y;
      t217 = t215 * t191 * t210;
      t219 = t122 * E;
      t220 = t123 * t219;
      t222 = t211 * t89 * t220;
      t225 = t215 * t89 * t220;
      t228 = t105 * t66 * t220;
      t229 = 12 * t228;
      t230 = I__y * M__y;
      t232 = t105 * t230 * t220;
      t233 = 12 * t232;
      t234 = -24 * t115 * t102 * G * t44 * l - t179 + t181 - t186 - t189 - t195 - t200 - t204 - 26 * t213 - 10 * t217 - 8 * t222 - 8 * t225 - t229 - t233;
      t240 = 0.1e1 / (t105 * t93 + t105 * t99 + t141);
      t241 = t240 * t112;
      out_5 = -t241 * l * (t175 + t234) / 4;
      t247 = t118 + t121 - t127 - t129 - t134 - t140 + 2 * t145 - 6 * t150 - 2 * t154 + t163 + t171 - t174;
      t253 = t105 * t51 * t210;
      t255 = t179 - t181 - t186 - t189 + t195 - t204 - 10 * t213 - 2 * t217 - 2 * t222 - 2 * t225 - t229 - t233 - 24 * t253;
      out_6 = -t241 * l * (t247 + t255) / 4;
      out_7 = out_1;
      t264 = F__x * K;
      t265 = l * t7;
      t268 = K * M__z;
      out_8 = -t29 * t28 * t26 * (-t7 * F__x * t16 - t7 * F__y * t16 - 2 * t265 * t264 + 2 * t268) * t7 / 4;
      t276 = F__x * t16;
      t277 = F__y * t16;
      t279 = F__y * K * l;
      out_9 = t30 * t26 * (t7 * t268 + t276 + t277 + 2 * t279) / 2;
      t285 = t123 * t135;
      t286 = T ^ 2;
      t287 = t286 * K;
      t288 = t95 * t2;
      t289 = t288 * t287;
      t291 = F__z * t165;
      t293 = t167 * t123;
      t297 = t122 * t165;
      t298 = t123 * t297;
      t299 = M__x * t167;
      t303 = M__y * t167;
      t307 = M__x * t176;
      t308 = t286 * t7;
      t309 = t2 * t308;
      t312 = M__y * t176;
      t318 = F__z * t44;
      t319 = t45 * t318;
      t322 = t99 * t54;
      t323 = t288 * t286;
      t327 = t168 * t166;
      t328 = K * M__x;
      t329 = t3 * t7;
      t330 = t329 * t328;
      t333 = t329 * t142;
      t336 = t183 * t182;
      t341 = t105 * t47;
      t344 = t7 * M__y;
      t345 = t105 * t344;
      t352 = t2 * t286;
      t356 = 48 * l * t293 * t122 * t291 + 36 * t352 * t47 * t103 + 48 * t161 * t167 * t291 + 36 * t7 * t299 * t298 + 36 * t7 * t303 * t298 + 8 * t323 * t89 * t322 + t289 * t285 + 16 * t289 * t319 + 36 * t309 * t307 + 36 * t309 * t312 + 60 * t330 * t327 + 12 * t333 * t327 + 72 * t341 * t327 + 72 * t345 * t327 + 12 * t330 * t336 + 12 * t333 * t336 + 36 * t341 * t336 + 36 * t345 * t336;
      t367 = T * t7;
      t368 = t95 * t367;
      t369 = t368 * t328;
      t372 = t368 * t142;
      t375 = t137 * t219;
      t388 = G * t291;
      t392 = t122 * t318;
      t402 = G * t318;
      t403 = t3 * t286;
      t407 = t122 * t54;
      t411 = K * t176;
      t418 = t160 * t286;
      t422 = 36 * t352 * t344 * t103 + 44 * t193 * t99 * t318 + 8 * t192 * t89 * t124 * t54 + 42 * t369 * t103 + 6 * t372 * t103 + 3 * t369 * t375 + 3 * t372 * t375 + 6 * t160 * t308 * t328 * t141 + 48 * t3 * t286 * t167 * t291 + 48 * t152 * t168 * t388 + 16 * t152 * t183 * t392 + 96 * t131 * t168 * t388 + 60 * t131 * t183 * t392 + 60 * t403 * t102 * t402 + 12 * t403 * t137 * t407 + 60 * t143 * t47 * t411 + 12 * t143 * t344 * t411 + 24 * t418 * t47 * t114;
      out_10 = t240 * t112 / I__y * t29 * t2 * (t356 + t422) / 24;
      t430 = I__x * t166;
      t437 = t123 * t182;
      t444 = t160 * t287;
      t466 = t286 * t45;
      t474 = 6 * t2 * t286 * I__y * t220 + 6 * t3 * K * t167 * t430 + 12 * l * T * t167 * t430 + 12 * l * T * t45 * t437 + 14 * t143 * t191 * t210 + 5 * t143 * t89 * t220 + 4 * t3 * t191 * t437 + 12 * t2 * t466 * t210 + 5 * t418 * t89 * t65 + t444 * t124 + 6 * t352 * t176 + 6 * t96 * t176 + 6 * t293 * t297 + 4 * t444 * t46;
      t475 = 0.1e1 / t474;
      t477 = t2 * t367;
      t486 = t288 * t94;
      t491 = t95 * t3 * t287;
      t501 = t95 * t7;
      t502 = t501 * t142;
      t505 = t501 * t328;
      t510 = t131 * t47;
      t527 = 12 * t477 * t307 - 12 * t477 * t312 + 24 * t3 * t308 * M__x * t46 + 20 * t486 * t319 + 8 * t491 * I__y * t54 + t486 * t285 + 2 * t491 * I__x * t80 + 12 * t2 * t183 * t392 + 4 * t502 * t103 + 5 * t505 * t375 + 5 * t502 * t375 + 48 * t510 * t103 + 14 * t288 * T * t89 * t322 + 12 * t510 * t375 + 12 * t131 * t344 * t375 + 24 * t403 * t47 * t141 + 32 * t505 * t103;
      t535 = t192 * t47;
      t538 = t192 * t344;
      t541 = K * t93;
      t542 = t323 * t47;
      t549 = K * t99;
      t565 = t160 * K;
      t572 = t3 * T;
      t583 = 26 * t160 * t367 * t328 * t141 + 12 * t95 * t466 * t318 + 32 * t535 * t114 + 4 * t538 * t114 + 16 * t542 * t541 + 2 * t535 * t125 + 2 * t538 * t125 + 4 * t542 * t549 + 12 * t265 * t299 * t430 - 12 * t265 * t303 * t430 + 12 * t265 * M__x * t45 * t437 + 12 * t265 * t51 * t437 + 20 * t565 * t102 * t402 + 4 * t565 * t137 * t407 + 24 * t572 * t102 * t402 + 12 * t572 * t137 * t407 + 12 * t95 * t286 * t56 * t55;
      out_11 = (t527 + t583) * t7 * t475 / 8;
      t589 = t286 * M__y;
      t590 = t160 * t589;
      t610 = -12 * t403 * t56 * t159 - 12 * t3 * t466 * t190 - 48 * t2 * t589 * t46 - 8 * t590 * t541 - 8 * t590 * t549 - t118 - 16 * t120 - 4 * t126 - 4 * t128 - 24 * t133 - 12 * t139 - 28 * t145 - 4 * t154 - t158 - 2 * t163 + 24 * t170;
      t627 = -48 * t352 * t230 * t65 - 24 * t173 + 24 * t178 - 24 * t180 - 24 * t185 - 24 * t188 - t195 - t200 - 12 * t203 - 8 * t213 - 16 * t217 - 10 * t222 - 10 * t225 - 24 * t228 - 24 * t232 - 96 * t253;
      out_12 = -t475 * (t610 + t627) * l / 8;
      out_13 = t32 * t26 * t24 * (2 * t5 + t18 - t11 + t14 + t22) / 6;
      out_14 = -t34 * t30 * t26 * (l * t264 + t276 + t277 + t279) * t7 / 2;

      % Store outputs
      out_d_f = zeros(14, 1);
      out_d_f(1) = out_1;
      out_d_f(2) = out_2;
      out_d_f(3) = out_3;
      out_d_f(4) = out_4;
      out_d_f(5) = out_5;
      out_d_f(6) = out_6;
      out_d_f(7) = out_7;
      out_d_f(8) = out_8;
      out_d_f(9) = out_9;
      out_d_f(10) = out_10;
      out_d_f(11) = out_11;
      out_d_f(12) = out_12;
      out_d_f(13) = out_13;
      out_d_f(14) = out_14;
    end % d_f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d_s = d_s( ~, ~, ~ )
      % Evaluate the deformation vector d_s.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d_s = sparse(10, 1);
    end % d_s
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f = f( this, ~, ~ )
      % Evaluate the force vector f.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;
      F__x = this.m_data.F__x;
      F__y = this.m_data.F__y;
      F__z = this.m_data.F__z;
      M__x = this.m_data.M__x;
      M__y = this.m_data.M__y;
      M__z = this.m_data.M__z;

      % Extract inputs
      % No inputs

      % Evaluate function
      t1 = 0.1e1 / l;
      t2 = F__x * l;
      t3 = F__y * l;
      t4 = sqrt(2);
      t5 = t4 * M__z;
      out_1 = -(t2 + t3 + t5) * t1 / 2;
      out_2 = -t1 * (t2 + t3 - t5) / 2;
      t12 = E ^ 2;
      t13 = I__y ^ 2;
      t14 = t13 * t12;
      t15 = t4 * M__x;
      t18 = t12 * t4;
      t19 = M__y * t13;
      t22 = F__z * E;
      t23 = G * t22;
      t24 = I__y * I__x;
      t28 = T * I__y;
      t29 = l ^ 2;
      t33 = G * E;
      t34 = I__x * t33;
      t35 = M__x * I__y;
      t39 = E * t4;
      t44 = I__y * t39;
      t45 = T * M__y;
      t46 = l * t45;
      t49 = F__z * G;
      t55 = t29 * l;
      t59 = K * I__y;
      t63 = E * I__y;
      t64 = T * K;
      t65 = t29 ^ 2;
      t66 = t65 * t64;
      t69 = G * I__x;
      t71 = G * t12;
      t72 = t13 * I__x;
      t73 = t72 * t71;
      t75 = T * l;
      t82 = 0.1e1 / (6 * t55 * K * t14 + 6 * l * t28 * t34 + 4 * t55 * t59 * t34 + 6 * t75 * t14 + 4 * t66 * t63 + t66 * t69 + 6 * t73);
      out_3 = -t82 * t29 * (3 * M__y * t24 * G * t39 + t29 * T * I__x * t49 + 4 * l * t24 * t23 + 4 * t29 * t28 * t22 + 3 * t4 * t35 * t34 - 6 * t15 * t14 + 6 * t19 * t18 + 6 * t46 * t44) * K / 2;
      t86 = G ^ 2;
      t87 = t86 * t12;
      t88 = I__x ^ 2;
      t89 = t13 * t88;
      t91 = M__x * t89 * t87;
      t92 = 12 * t91;
      t94 = M__y * t89 * t87;
      t95 = 12 * t94;
      t96 = F__z * t18;
      t97 = K * t13;
      t98 = t65 * l;
      t99 = t98 * T;
      t100 = t99 * t97;
      t102 = 4 * t100 * t96;
      t107 = t99 * K * t88 * t86 * F__z * t4;
      t108 = t88 * t86;
      t111 = l * t13 * t108 * t96;
      t112 = 6 * t111;
      t115 = M__x * T;
      t119 = I__x * t71;
      t120 = t55 * M__x;
      t122 = t120 * t97 * t119;
      t124 = t55 * M__y;
      t126 = t124 * t97 * t119;
      t128 = t86 * E;
      t129 = t88 * t128;
      t131 = t120 * t59 * t129;
      t134 = t124 * t59 * t129;
      t137 = t75 * t35 * t129;
      t138 = 12 * t137;
      t139 = I__y * M__y;
      t141 = t75 * t139 * t129;
      t142 = 12 * t141;
      t143 = K * t14;
      t144 = t65 * t115;
      t146 = 8 * t144 * t143;
      t147 = -24 * G * l * t115 * t12 * t72 - t102 - t107 - t112 - 26 * t122 - 10 * t126 - 8 * t131 - 8 * t134 - t138 - t142 - t146 - t92 - t95;
      t148 = t65 * t45;
      t149 = t148 * t143;
      t150 = 4 * t149;
      t151 = K * t108;
      t152 = t144 * t151;
      t153 = 2 * t152;
      t154 = t148 * t151;
      t155 = 2 * t154;
      t156 = t12 * E;
      t157 = G * t156;
      t158 = t13 * I__y;
      t159 = t158 * I__x;
      t161 = M__x * t159 * t157;
      t162 = 12 * t161;
      t164 = M__y * t159 * t157;
      t165 = 12 * t164;
      t166 = t158 * t156;
      t168 = l * t115 * t166;
      t169 = 12 * t168;
      t170 = t46 * t166;
      t171 = 12 * t170;
      t172 = t24 * t33;
      t173 = K * M__y;
      t174 = t65 * T;
      t176 = t174 * t173 * t172;
      t181 = t115 * t59 * t69 * E * t65;
      t183 = t49 * t18;
      t184 = t65 * K;
      t186 = t184 * t72 * t183;
      t188 = t86 * F__z;
      t189 = t188 * t39;
      t190 = I__y * t88;
      t193 = 4 * t184 * t190 * t189;
      t194 = t29 * T;
      t196 = t194 * t72 * t183;
      t197 = 6 * t196;
      t199 = t194 * t190 * t189;
      t200 = 6 * t199;
      t201 = t49 * t39;
      t202 = t98 * t64;
      t204 = t202 * t24 * t201;
      t206 = -t150 - t153 - t155 - t162 + t165 - t169 + t171 - 6 * t176 - 10 * t181 - 10 * t186 - t193 - t197 - t200 - 5 * t204;
      t213 = 0.1e1 / (t63 * t75 + t69 * t75 + t172);
      t214 = t213 * t82 * l;
      out_4 = t214 * (t147 + t206) * T / 4;
      t221 = t75 * t19 * t119;
      t223 = -t92 - t95 + t102 - t112 - 10 * t122 - 2 * t126 - 2 * t131 - 2 * t134 - t138 - t142 - 24 * t221 + t146;
      t227 = t150 - t153 - t155 + t162 - t165 + t169 - t171 + 2 * t176 - 6 * t181 - 2 * t186 - t197 - t200 + t204;
      out_5 = t214 * (t223 + t227) * T / 4;
      out_13 = F__x;
      out_14 = F__y;
      out_15 = F__z;
      out_16 = M__x;
      out_17 = M__y;
      out_18 = M__z;
      t231 = t29 * A;
      t232 = 3 * I__z;
      t234 = 0.1e1 / t55;
      t235 = t234 * (t231 + t232);
      t237 = A * E;
      t242 = F__x * K;
      t243 = l * t4;
      t246 = K * M__z;
      t249 = 0.1e1 / K;
      t251 = 0.1e1 / A;
      t252 = t251 * t249 * (-F__x * t237 * t4 - F__y * t237 * t4 - 2 * t242 * t243 + 2 * t246);
      t256 = t234 * (t231 - t232);
      t257 = F__x * t237;
      t258 = F__y * t237;
      t260 = F__y * K * l;
      t265 = t251 * t249 * (t246 * t4 + t257 + t258 + 2 * t260);
      t274 = 0.3e1 / 0.2e1 * t251 * t249 * (l * t242 + t257 + t258 + t260) * t234 * I__z;
      out_19 = t252 * t4 * t235 / 8 + t265 * t256 / 4 + t274;
      out_20 = -t252 * t4 * t256 / 8 - t265 * t235 / 4 + t274;
      t280 = F__z * t156;
      t281 = T ^ 2;
      t286 = G * t280;
      t290 = F__z * t12;
      t291 = t86 * t290;
      t301 = G * t290;
      t302 = t55 * t281;
      t306 = t86 * t22;
      t310 = K * t166;
      t314 = t4 * M__y;
      t318 = t98 * t281;
      t322 = M__y * t166;
      t323 = t281 * t4;
      t324 = t29 * t323;
      t330 = t13 * t290;
      t331 = t281 * K;
      t332 = t65 * t29;
      t333 = t332 * t331;
      t336 = t88 * t188;
      t339 = t158 * t88;
      t343 = t86 * t156;
      t344 = t88 * t343;
      t345 = M__x * t158;
      t349 = M__y * t158;
      t353 = M__x * t166;
      t356 = 48 * t55 * t281 * t158 * t280 + 48 * t184 * t159 * t286 + 16 * t184 * t89 * t291 + 96 * t194 * t159 * t286 + 60 * t194 * t89 * t291 + 60 * t302 * t72 * t301 + 12 * t302 * t190 * t306 + 60 * t174 * t15 * t310 + 12 * t174 * t314 * t310 + 24 * t318 * t15 * t143 + 36 * t324 * t322 + 48 * t202 * t158 * t280 + 16 * t333 * t330 + t333 * t336 + 48 * l * t339 * t86 * t280 + 36 * t4 * t345 * t344 + 36 * t4 * t349 * t344 + 36 * t324 * t353;
      t364 = t69 * t22;
      t365 = t332 * t281;
      t369 = t159 * t157;
      t370 = K * M__x;
      t371 = t55 * t4;
      t372 = t371 * t370;
      t375 = t371 * t173;
      t378 = t89 * t87;
      t383 = t75 * t15;
      t386 = t75 * t314;
      t393 = t29 * t281;
      t404 = T * t4;
      t405 = t65 * t404;
      t406 = t405 * t370;
      t409 = t405 * t173;
      t412 = t190 * t128;
      t417 = 8 * t108 * t22 * t59 * t99 + 6 * t172 * t323 * t370 * t98 + 44 * t100 * t290 * t69 + 36 * t15 * t393 * t73 + 36 * t314 * t393 * t73 + 8 * t364 * t365 * t59 + 60 * t369 * t372 + 12 * t369 * t375 + 72 * t369 * t383 + 72 * t369 * t386 + 12 * t372 * t378 + 12 * t375 * t378 + 36 * t378 * t383 + 36 * t378 * t386 + 3 * t406 * t412 + 42 * t406 * t73 + 3 * t409 * t412 + 6 * t409 * t73;
      t418 = t356 + t417;
      t420 = t213 * t82;
      t424 = I__x * t157;
      t431 = t88 * t87;
      t438 = t98 * t331;
      t460 = t281 * t13;
      t468 = 6 * I__y * t129 * t281 * t29 + 6 * K * t158 * t424 * t55 + 12 * T * l * t13 * t431 + 12 * T * l * t158 * t424 + 14 * t119 * t174 * t97 + 12 * t119 * t29 * t460 + 5 * t129 * t174 * t59 + 5 * t318 * t34 * t59 + 4 * t431 * t55 * t97 + t108 * t438 + 4 * t14 * t438 + 6 * t166 * t393 + 6 * t166 * t66 + 6 * t339 * t343;
      t469 = 0.1e1 / t468;
      t474 = t99 * t15;
      t477 = t99 * t314;
      t480 = K * t63;
      t481 = t365 * t15;
      t488 = K * t69;
      t504 = t98 * K;
      t511 = t55 * T;
      t522 = t29 * t404;
      t525 = 12 * M__x * t13 * t243 * t431 + 12 * t23 * t24 * t281 * t65 + 12 * t19 * t243 * t431 + 4 * t190 * t306 * t504 + 12 * t190 * t306 * t511 + 12 * t243 * t345 * t424 - 12 * t243 * t349 * t424 + 12 * t290 * t460 * t65 + 20 * t301 * t504 * t72 + 24 * t301 * t511 * t72 + 32 * t143 * t474 + 4 * t143 * t477 + 2 * t151 * t474 + 2 * t151 * t477 + 12 * t353 * t522 + 16 * t480 * t481 + 4 * t481 * t488;
      t532 = t332 * t64;
      t537 = t65 * t55 * t331;
      t551 = t194 * t15;
      t560 = t65 * t4;
      t561 = t560 * t370;
      t564 = t560 * t173;
      t577 = -12 * t522 * t322 + 24 * t55 * t323 * M__x * t14 + 20 * t532 * t330 + 8 * t537 * I__y * t22 + t532 * t336 + 2 * t537 * I__x * t49 + 12 * t29 * t89 * t291 + 14 * t332 * T * t59 * t364 + 12 * t551 * t412 + 12 * t194 * t314 * t412 + 24 * t302 * t15 * t172 + 32 * t561 * t73 + 4 * t564 * t73 + 5 * t561 * t412 + 5 * t564 * t412 + 48 * t551 * t73 + 26 * t98 * t404 * t370 * t172;
      t578 = t525 + t577;
      t582 = t281 * M__y;
      t598 = -48 * t14 * t29 * t582 - t102 - t107 - 12 * t111 - 8 * t122 - 16 * t126 - 10 * t131 - 10 * t134 - 24 * t137 - 24 * t141 - t146 - 16 * t149 - 4 * t152 - 96 * t221 - 24 * t91 - 24 * t94;
      t607 = t98 * t582;
      t623 = -48 * t139 * t34 * t393 - 12 * t201 * t24 * t302 - 12 * t460 * t55 * t96 - 8 * t480 * t607 - 8 * t488 * t607 - 4 * t154 + 24 * t161 - 24 * t164 + 24 * t168 - 24 * t170 - 28 * t176 - 4 * t186 - t193 - 24 * t196 - 12 * t199 - 2 * t204;
      t624 = t598 + t623;
      out_21 = -t420 * t418 * t1 / 2 + 0.3e1 / 0.4e1 * t578 * t469 / t29 * t63 - 0.3e1 / 0.8e1 * t469 * t624 * t1 * t44;
      t631 = t420 * t418 * t4 / 8;
      t632 = 2 * t63;
      t633 = t632 - t69;
      t636 = t578 * t4 * t469;
      t639 = t632 + t69;
      out_22 = -t631 + t636 * t1 * t633 / 16 - t469 * t624 * t639 / 16;
      out_23 = -t631 + t636 * t1 * t639 / 16 - t469 * t624 * t633 / 16;

      % Store outputs
      out_f = zeros(24, 1);
      out_f(1) = out_1;
      out_f(2) = out_2;
      out_f(3) = out_3;
      out_f(4) = out_4;
      out_f(5) = out_5;
      out_f(13) = out_13;
      out_f(14) = out_14;
      out_f(15) = out_15;
      out_f(16) = out_16;
      out_f(17) = out_17;
      out_f(18) = out_18;
      out_f(19) = out_19;
      out_f(20) = out_20;
      out_f(21) = out_21;
      out_f(22) = out_22;
      out_f(23) = out_23;
    end % f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_f = f_f( this, ~, ~ )
      % Evaluate the force vector f_f.

      % Extract properties
      F__x = this.m_data.F__x;
      F__y = this.m_data.F__y;
      F__z = this.m_data.F__z;
      M__x = this.m_data.M__x;
      M__y = this.m_data.M__y;
      M__z = this.m_data.M__z;

      % Extract inputs
      % No inputs

      % Evaluate function
      out_8 = F__x;
      out_9 = F__y;
      out_10 = F__z;
      out_11 = M__x;
      out_12 = M__y;
      out_13 = M__z;

      % Store outputs
      out_f_f = sparse(14, 1);
      out_f_f(8) = out_8;
      out_f_f(9) = out_9;
      out_f_f(10) = out_10;
      out_f_f(11) = out_11;
      out_f_f(12) = out_12;
      out_f_f(13) = out_13;
    end % f_f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_s = f_s( this, ~, ~ )
      % Evaluate the force vector f_s.

      % Extract properties
      E = this.m_data.E;
      G = this.m_data.G;
      A = this.m_data.A;
      I__x = this.m_data.I__x;
      I__y = this.m_data.I__y;
      I__z = this.m_data.I__z;
      K = this.m_data.K;
      T = this.m_data.T;
      l = this.m_data.l;
      F__x = this.m_data.F__x;
      F__y = this.m_data.F__y;
      F__z = this.m_data.F__z;
      M__x = this.m_data.M__x;
      M__y = this.m_data.M__y;
      M__z = this.m_data.M__z;

      % Extract inputs
      % No inputs

      % Evaluate function
      t1 = 0.1e1 / l;
      t2 = F__x * l;
      t3 = F__y * l;
      t4 = sqrt(2);
      t5 = t4 * M__z;
      out_1 = -(t2 + t3 + t5) * t1 / 2;
      out_2 = -t1 * (t2 + t3 - t5) / 2;
      t12 = E ^ 2;
      t13 = I__y ^ 2;
      t14 = t13 * t12;
      t15 = t4 * M__x;
      t18 = t12 * t4;
      t19 = M__y * t13;
      t22 = F__z * E;
      t23 = G * t22;
      t24 = I__y * I__x;
      t28 = T * I__y;
      t29 = l ^ 2;
      t33 = G * E;
      t34 = I__x * t33;
      t35 = M__x * I__y;
      t39 = E * t4;
      t44 = I__y * t39;
      t45 = T * M__y;
      t46 = l * t45;
      t49 = F__z * G;
      t55 = t29 * l;
      t59 = K * I__y;
      t63 = E * I__y;
      t64 = T * K;
      t65 = t29 ^ 2;
      t66 = t65 * t64;
      t69 = G * I__x;
      t71 = G * t12;
      t72 = t13 * I__x;
      t73 = t72 * t71;
      t75 = T * l;
      t82 = 0.1e1 / (6 * t55 * K * t14 + 6 * l * t28 * t34 + 4 * t55 * t59 * t34 + 6 * t75 * t14 + 4 * t66 * t63 + t66 * t69 + 6 * t73);
      out_3 = -t82 * t29 * (3 * M__y * t24 * G * t39 + t29 * T * I__x * t49 + 4 * l * t24 * t23 + 4 * t29 * t28 * t22 + 3 * t4 * t35 * t34 - 6 * t15 * t14 + 6 * t19 * t18 + 6 * t46 * t44) * K / 2;
      t86 = t24 * t33;
      t87 = K * M__y;
      t88 = t65 * T;
      t90 = t88 * t87 * t86;
      t94 = M__x * T;
      t96 = t94 * t59 * t69 * E * t65;
      t98 = t49 * t18;
      t99 = t65 * K;
      t101 = t99 * t72 * t98;
      t103 = G ^ 2;
      t104 = t103 * F__z;
      t105 = t104 * t39;
      t106 = I__x ^ 2;
      t107 = I__y * t106;
      t110 = 4 * t99 * t107 * t105;
      t111 = t29 * T;
      t113 = t111 * t72 * t98;
      t114 = 6 * t113;
      t116 = t111 * t107 * t105;
      t117 = 6 * t116;
      t118 = t49 * t39;
      t119 = t65 * l;
      t120 = t119 * t64;
      t122 = t120 * t24 * t118;
      t124 = K * t14;
      t125 = t65 * t94;
      t127 = 8 * t125 * t124;
      t128 = t65 * t45;
      t129 = t128 * t124;
      t130 = 4 * t129;
      t131 = t106 * t103;
      t132 = K * t131;
      t133 = t125 * t132;
      t134 = 2 * t133;
      t135 = t128 * t132;
      t136 = 2 * t135;
      t137 = F__z * t18;
      t138 = K * t13;
      t139 = t119 * T;
      t140 = t139 * t138;
      t142 = 4 * t140 * t137;
      t147 = t139 * K * t106 * t103 * F__z * t4;
      t148 = -6 * t90 - 10 * t96 - 10 * t101 - t110 - t114 - t117 - 5 * t122 - t127 - t130 - t134 - t136 - t142 - t147;
      t151 = l * t13 * t131 * t137;
      t152 = 6 * t151;
      t158 = I__x * t71;
      t159 = t55 * M__x;
      t161 = t159 * t138 * t158;
      t163 = t55 * M__y;
      t165 = t163 * t138 * t158;
      t167 = t103 * E;
      t168 = t106 * t167;
      t170 = t159 * t59 * t168;
      t173 = t163 * t59 * t168;
      t176 = t75 * t35 * t168;
      t177 = 12 * t176;
      t178 = I__y * M__y;
      t180 = t75 * t178 * t168;
      t181 = 12 * t180;
      t182 = t12 * E;
      t183 = G * t182;
      t184 = t13 * I__y;
      t185 = t184 * I__x;
      t187 = M__x * t185 * t183;
      t188 = 12 * t187;
      t190 = M__y * t185 * t183;
      t191 = 12 * t190;
      t192 = t184 * t182;
      t194 = l * t94 * t192;
      t195 = 12 * t194;
      t196 = t46 * t192;
      t197 = 12 * t196;
      t198 = t103 * t12;
      t199 = t13 * t106;
      t201 = M__x * t199 * t198;
      t202 = 12 * t201;
      t204 = M__y * t199 * t198;
      t205 = 12 * t204;
      t206 = -24 * t94 * t72 * G * t12 * l - t152 - 26 * t161 - 10 * t165 - 8 * t170 - 8 * t173 - t177 - t181 - t188 + t191 - t195 + t197 - t202 - t205;
      t213 = 0.1e1 / (t63 * t75 + t69 * t75 + t86);
      t214 = t213 * t82 * l;
      out_4 = t214 * (t148 + t206) * T / 4;
      t220 = t75 * t19 * t158;
      t222 = 2 * t90 - 6 * t96 - 2 * t101 - t114 - t117 + t122 + t127 + t130 - t134 - t136 - 24 * t220 + t142;
      t227 = -t152 - 10 * t161 - 2 * t165 - 2 * t170 - 2 * t173 - t177 - t181 + t188 - t191 + t195 - t197 - t202 - t205;
      out_5 = t214 * (t222 + t227) * T / 4;
      t231 = t29 * A;
      t232 = 3 * I__z;
      t234 = 0.1e1 / t55;
      t235 = t234 * (t231 + t232);
      t237 = A * E;
      t242 = F__x * K;
      t243 = l * t4;
      t246 = K * M__z;
      t249 = 0.1e1 / K;
      t251 = 0.1e1 / A;
      t252 = t251 * t249 * (-F__x * t237 * t4 - F__y * t237 * t4 - 2 * t242 * t243 + 2 * t246);
      t256 = t234 * (t231 - t232);
      t257 = F__x * t237;
      t258 = F__y * t237;
      t260 = F__y * K * l;
      t265 = t251 * t249 * (t246 * t4 + t257 + t258 + 2 * t260);
      t274 = 0.3e1 / 0.2e1 * t251 * t249 * (l * t242 + t257 + t258 + t260) * t234 * I__z;
      out_6 = t252 * t4 * t235 / 8 + t265 * t256 / 4 + t274;
      out_7 = -t252 * t4 * t256 / 8 - t265 * t235 / 4 + t274;
      t280 = F__z * t12;
      t288 = t69 * t22;
      t289 = T ^ 2;
      t290 = t65 * t29;
      t291 = t290 * t289;
      t295 = t185 * t183;
      t296 = K * M__x;
      t297 = t55 * t4;
      t298 = t297 * t296;
      t301 = t297 * t87;
      t304 = t199 * t198;
      t309 = t75 * t15;
      t312 = t4 * M__y;
      t313 = t75 * t312;
      t320 = t29 * t289;
      t327 = T * t4;
      t328 = t65 * t327;
      t329 = t328 * t296;
      t332 = t328 * t87;
      t335 = t107 * t167;
      t340 = t289 * t4;
      t345 = 6 * t119 * t340 * t296 * t86 + 8 * t139 * t59 * t131 * t22 + 44 * t140 * t69 * t280 + 36 * t320 * t15 * t73 + 8 * t291 * t59 * t288 + 36 * t320 * t312 * t73 + 60 * t298 * t295 + 12 * t301 * t295 + 72 * t309 * t295 + 72 * t313 * t295 + 12 * t298 * t304 + 12 * t301 * t304 + 36 * t309 * t304 + 36 * t313 * t304 + 3 * t329 * t335 + 42 * t329 * t73 + 3 * t332 * t335 + 6 * t332 * t73;
      t346 = t13 * t280;
      t347 = t289 * K;
      t348 = t290 * t347;
      t351 = t106 * t104;
      t353 = F__z * t182;
      t355 = t184 * t106;
      t359 = t103 * t182;
      t360 = t106 * t359;
      t361 = M__x * t184;
      t365 = M__y * t184;
      t369 = M__x * t192;
      t370 = t29 * t340;
      t373 = M__y * t192;
      t379 = G * t353;
      t383 = t103 * t280;
      t393 = G * t280;
      t394 = t55 * t289;
      t398 = t103 * t22;
      t402 = K * t192;
      t409 = t119 * t289;
      t417 = 16 * t348 * t346 + t348 * t351 + 48 * l * t355 * t103 * t353 + 36 * t4 * t361 * t360 + 36 * t4 * t365 * t360 + 36 * t370 * t369 + 36 * t370 * t373 + 48 * t120 * t184 * t353 + 48 * t99 * t185 * t379 + 16 * t99 * t199 * t383 + 96 * t111 * t185 * t379 + 60 * t111 * t199 * t383 + 60 * t394 * t72 * t393 + 12 * t394 * t107 * t398 + 60 * t88 * t15 * t402 + 12 * t88 * t312 * t402 + 24 * t409 * t15 * t124 + 48 * t55 * t289 * t184 * t353;
      t418 = t345 + t417;
      t420 = t213 * t82;
      t424 = I__x * t183;
      t431 = t106 * t198;
      t438 = t119 * t347;
      t460 = t289 * t13;
      t468 = 6 * t29 * t289 * I__y * t168 + 6 * t55 * K * t184 * t424 + 12 * T * l * t13 * t431 + 12 * l * T * t184 * t424 + 14 * t88 * t138 * t158 + 4 * t55 * t138 * t431 + 12 * t29 * t460 * t158 + 5 * t88 * t59 * t168 + 5 * t409 * t59 * t34 + t438 * t131 + 4 * t14 * t438 + 6 * t320 * t192 + 6 * t66 * t192 + 6 * t355 * t359;
      t469 = 0.1e1 / t468;
      t475 = t111 * t15;
      t484 = t65 * t4;
      t485 = t484 * t296;
      t488 = t484 * t87;
      t501 = t29 * t327;
      t510 = t290 * t64;
      t515 = t65 * t55 * t347;
      t522 = 14 * t290 * T * t59 * t288 + 12 * t475 * t335 + 12 * t111 * t312 * t335 + 24 * t394 * t15 * t86 + 32 * t485 * t73 + 4 * t488 * t73 + 5 * t485 * t335 + 5 * t488 * t335 + 48 * t475 * t73 + 26 * t119 * t327 * t296 * t86 + 12 * t501 * t369 - 12 * t501 * t373 + 24 * t55 * t340 * M__x * t14 + 20 * t510 * t346 + 8 * t515 * I__y * t22 + t510 * t351 + 2 * t515 * I__x * t49;
      t526 = t139 * t15;
      t529 = t139 * t312;
      t532 = K * t63;
      t533 = t291 * t15;
      t540 = K * t69;
      t556 = t119 * K;
      t563 = t55 * T;
      t577 = 12 * M__x * t13 * t243 * t431 + 12 * t65 * t289 * t24 * t23 + 4 * t556 * t107 * t398 + 12 * t563 * t107 * t398 + 12 * t19 * t243 * t431 + 12 * t29 * t199 * t383 + 12 * t243 * t361 * t424 - 12 * t243 * t365 * t424 + 12 * t65 * t460 * t280 + 20 * t556 * t72 * t393 + 24 * t563 * t72 * t393 + 32 * t526 * t124 + 4 * t529 * t124 + 2 * t526 * t132 + 2 * t529 * t132 + 16 * t533 * t532 + 4 * t533 * t540;
      t578 = t522 + t577;
      t593 = t289 * M__y;
      t594 = t119 * t593;
      t606 = -12 * t394 * t24 * t118 - 12 * t55 * t460 * t137 - 48 * t320 * t178 * t34 - 8 * t594 * t532 - 8 * t594 * t540 - 4 * t101 - t110 - 24 * t113 - 12 * t116 - 2 * t122 - t127 - 16 * t129 - 4 * t133 - 4 * t135 - 96 * t220 - 28 * t90;
      t623 = -48 * t29 * t593 * t14 - t142 - t147 - 12 * t151 - 8 * t161 - 16 * t165 - 10 * t170 - 10 * t173 - 24 * t176 - 24 * t180 + 24 * t187 - 24 * t190 + 24 * t194 - 24 * t196 - 24 * t201 - 24 * t204;
      t624 = t606 + t623;
      out_8 = -t420 * t418 * t1 / 2 + 0.3e1 / 0.4e1 * t578 * t469 / t29 * t63 - 0.3e1 / 0.8e1 * t469 * t624 * t1 * t44;
      t631 = t420 * t418 * t4 / 8;
      t632 = 2 * t63;
      t633 = t632 - t69;
      t636 = t578 * t4 * t469;
      t639 = t632 + t69;
      out_9 = -t631 + t636 * t1 * t633 / 16 - t469 * t624 * t639 / 16;
      out_10 = -t631 + t636 * t1 * t639 / 16 - t469 * t624 * t633 / 16;

      % Store outputs
      out_f_s = zeros(10, 1);
      out_f_s(1) = out_1;
      out_f_s(2) = out_2;
      out_f_s(3) = out_3;
      out_f_s(4) = out_4;
      out_f_s(5) = out_5;
      out_f_s(6) = out_6;
      out_f_s(7) = out_7;
      out_f_s(8) = out_8;
      out_f_s(9) = out_9;
      out_f_s(10) = out_10;
    end % f_s
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_r = f_r( ~, ~, ~ )
      % Evaluate the force vector f_r.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_r = sparse(10, 1);
    end % f_r
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_perm = perm( ~ )
      % Evaluate the permutation vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_perm = zeros(24, 1);
      out_perm(1) = 6;
      out_perm(2) = 7;
      out_perm(3) = 8;
      out_perm(4) = 9;
      out_perm(5) = 10;
      out_perm(6) = 11;
      out_perm(7) = 12;
      out_perm(8) = 13;
      out_perm(9) = 14;
      out_perm(10) = 15;
      out_perm(11) = 16;
      out_perm(12) = 17;
      out_perm(13) = 18;
      out_perm(14) = 24;
      out_perm(15) = 1;
      out_perm(16) = 2;
      out_perm(17) = 3;
      out_perm(18) = 4;
      out_perm(19) = 5;
      out_perm(20) = 19;
      out_perm(21) = 20;
      out_perm(22) = 21;
      out_perm(23) = 22;
      out_perm(24) = 23;
    end % perm
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_unperm = unperm( ~ )
      % Evaluate the unpermutation vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_unperm = zeros(24, 1);
      out_unperm(1) = 15;
      out_unperm(2) = 16;
      out_unperm(3) = 17;
      out_unperm(4) = 18;
      out_unperm(5) = 19;
      out_unperm(6) = 1;
      out_unperm(7) = 2;
      out_unperm(8) = 3;
      out_unperm(9) = 4;
      out_unperm(10) = 5;
      out_unperm(11) = 6;
      out_unperm(12) = 7;
      out_unperm(13) = 8;
      out_unperm(14) = 9;
      out_unperm(15) = 10;
      out_unperm(16) = 11;
      out_unperm(17) = 12;
      out_unperm(18) = 13;
      out_unperm(19) = 20;
      out_unperm(20) = 21;
      out_unperm(21) = 22;
      out_unperm(22) = 23;
      out_unperm(23) = 24;
      out_unperm(24) = 14;
    end % unperm
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( ~, ~ )
      % Evaluate the veiling vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_v = zeros(0, 1);
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % Test_10

% That's All Folks!
