% +--------------------------------------------------------------------------+
% | 'TrussMe' module version 0.0 - BSD 3-Clause License - Copyright (c) 2023 |
% | Current version authors:                                                 |
% |   Davide Stocco and Matteo Larcher.                                      |
% +--------------------------------------------------------------------------+

% Matlab generated code for system: Test_03
% This file has been automatically generated by TrussMe.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef Test_03 < TrussMe.System
  %
  % Test_03 class
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = Test_03( varargin )
      % Class constructor.

      % User data
      if (nargin == 0)
        data = [];
      elseif (nargin == 1 && isstruct(varargin{1}))
        data = varargin{1};
      else
        error('wrong number of input arguments.');
      end

      % Call superclass constructor
      this = this@TrussMe.System(data);
    end % Test_03
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K = K( ~, ~, ~ )
      % Evaluate the stiffness matrix K.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K = sparse(24, 24);
      out_K(2, 2) = 2666666.667;
      out_K(8, 2) = -2666666.667;
      out_K(5, 5) = .6666666667e11;
      out_K(11, 5) = -.6666666667e11;
      out_K(7, 7) = 3026052.104;
      out_K(8, 7) = 769539.0782;
      out_K(13, 7) = -1026052.104;
      out_K(14, 7) = -769539.0782;
      out_K(19, 7) = -2000000.;
      out_K(2, 8) = -2666666.667;
      out_K(7, 8) = 769539.0782;
      out_K(8, 8) = 3243820.976;
      out_K(13, 8) = -769539.0782;
      out_K(14, 8) = -577154.3087;
      out_K(10, 10) = .7565130260e11;
      out_K(11, 10) = .1923847695e11;
      out_K(16, 10) = -.2565130260e11;
      out_K(17, 10) = -.1923847695e11;
      out_K(22, 10) = -.5000000000e11;
      out_K(5, 11) = -.6666666667e11;
      out_K(10, 11) = .1923847695e11;
      out_K(11, 11) = .8109552439e11;
      out_K(16, 11) = -.1923847695e11;
      out_K(17, 11) = -.1442885772e11;
      out_K(7, 13) = -1026052.104;
      out_K(8, 13) = -769539.0782;
      out_K(13, 13) = 1026052.104;
      out_K(14, 13) = 769539.0782;
      out_K(7, 14) = -769539.0782;
      out_K(8, 14) = -577154.3087;
      out_K(13, 14) = 769539.0782;
      out_K(14, 14) = 577154.3087;
      out_K(10, 16) = -.2565130260e11;
      out_K(11, 16) = -.1923847695e11;
      out_K(16, 16) = .2565130260e11;
      out_K(17, 16) = .1923847695e11;
      out_K(10, 17) = -.1923847695e11;
      out_K(11, 17) = -.1442885772e11;
      out_K(16, 17) = .1923847695e11;
      out_K(17, 17) = .1442885772e11;
      out_K(7, 19) = -2000000.;
      out_K(19, 19) = 2000000.;
      out_K(10, 22) = -.5000000000e11;
      out_K(22, 22) = .5000000000e11;
    end % K
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_ff = K_ff( ~, ~, ~ )
      % Evaluate the stiffness matrix K_ff.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_ff = zeros(4, 4);
      out_K_ff(1, 1) = 3026052.104;
      out_K_ff(2, 1) = 769539.0782;
      out_K_ff(1, 2) = 769539.0782;
      out_K_ff(2, 2) = 3243820.976;
      out_K_ff(3, 3) = .7565130260e11;
      out_K_ff(4, 3) = .1923847695e11;
      out_K_ff(3, 4) = .1923847695e11;
      out_K_ff(4, 4) = .8109552439e11;
    end % K_ff
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_fs = K_fs( ~, ~, ~ )
      % Evaluate the stiffness matrix K_fs.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_fs = sparse(4, 20);
      out_K_fs(2, 2) = -2666666.667;
      out_K_fs(4, 5) = -.6666666667e11;
      out_K_fs(1, 9) = -1026052.104;
      out_K_fs(2, 9) = -769539.0782;
      out_K_fs(1, 10) = -769539.0782;
      out_K_fs(2, 10) = -577154.3087;
      out_K_fs(3, 12) = -.2565130260e11;
      out_K_fs(4, 12) = -.1923847695e11;
      out_K_fs(3, 13) = -.1923847695e11;
      out_K_fs(4, 13) = -.1442885772e11;
      out_K_fs(1, 15) = -2000000.;
      out_K_fs(3, 18) = -.5000000000e11;
    end % K_fs
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_sf = K_sf( ~, ~, ~ )
      % Evaluate the stiffness matrix K_sf.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_sf = sparse(20, 4);
      out_K_sf(9, 1) = -1026052.104;
      out_K_sf(10, 1) = -769539.0782;
      out_K_sf(15, 1) = -2000000.;
      out_K_sf(2, 2) = -2666666.667;
      out_K_sf(9, 2) = -769539.0782;
      out_K_sf(10, 2) = -577154.3087;
      out_K_sf(12, 3) = -.2565130260e11;
      out_K_sf(13, 3) = -.1923847695e11;
      out_K_sf(18, 3) = -.5000000000e11;
      out_K_sf(5, 4) = -.6666666667e11;
      out_K_sf(12, 4) = -.1923847695e11;
      out_K_sf(13, 4) = -.1442885772e11;
    end % K_sf
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_K_ss = K_ss( ~, ~, ~ )
      % Evaluate the stiffness matrix K_ss.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_K_ss = sparse(20, 20);
      out_K_ss(2, 2) = 2666666.667;
      out_K_ss(5, 5) = .6666666667e11;
      out_K_ss(9, 9) = 1026052.104;
      out_K_ss(10, 9) = 769539.0782;
      out_K_ss(9, 10) = 769539.0782;
      out_K_ss(10, 10) = 577154.3087;
      out_K_ss(12, 12) = .2565130260e11;
      out_K_ss(13, 12) = .1923847695e11;
      out_K_ss(12, 13) = .1923847695e11;
      out_K_ss(13, 13) = .1442885772e11;
      out_K_ss(15, 15) = 2000000.;
      out_K_ss(18, 18) = .5000000000e11;
    end % K_ss
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d = d( ~, ~, ~ )
      % Evaluate the deformation vector d.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d = sparse(24, 1);
      out_d(7) = -.00370057937465289;
      out_d(8) = -.0020815758974313;
    end % d
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d_f = d_f( ~, ~, ~ )
      % Evaluate the deformation vector d_f.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d_f = zeros(4, 1);
      out_d_f(1) = -.00370057937465289;
      out_d_f(2) = -.0020815758974313;
    end % d_f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_d_s = d_s( ~, ~, ~ )
      % Evaluate the deformation vector d_s.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_d_s = sparse(20, 1);
    end % d_s
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f = f( ~, ~, ~ )
      % Evaluate the force vector f.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f = sparse(24, 1);
      out_f(2) = 5550.86906051066;
      out_f(7) = -12800.;
      out_f(8) = -9600.;
      out_f(13) = 5398.84125069422;
      out_f(14) = 4049.13093886486;
      out_f(19) = 7401.15874930578;
    end % f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_f = f_f( ~, ~, ~ )
      % Evaluate the force vector f_f.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_f = zeros(4, 1);
      out_f_f(1) = -12800.;
      out_f_f(2) = -9600.;
    end % f_f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_s = f_s( ~, ~, ~ )
      % Evaluate the force vector f_s.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_s = sparse(20, 1);
      out_f_s(2) = 5550.86906051066;
      out_f_s(9) = 5398.84125069422;
      out_f_s(10) = 4049.13093886486;
      out_f_s(15) = 7401.15874930578;
    end % f_s
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f_r = f_r( ~, ~, ~ )
      % Evaluate the force vector f_r.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_f_r = sparse(20, 1);
    end % f_r
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_perm = perm( ~ )
      % Evaluate the permutation vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_perm = zeros(24, 1);
      out_perm(1) = 7;
      out_perm(2) = 8;
      out_perm(3) = 10;
      out_perm(4) = 11;
      out_perm(5) = 1;
      out_perm(6) = 2;
      out_perm(7) = 3;
      out_perm(8) = 4;
      out_perm(9) = 5;
      out_perm(10) = 6;
      out_perm(11) = 9;
      out_perm(12) = 12;
      out_perm(13) = 13;
      out_perm(14) = 14;
      out_perm(15) = 15;
      out_perm(16) = 16;
      out_perm(17) = 17;
      out_perm(18) = 18;
      out_perm(19) = 19;
      out_perm(20) = 20;
      out_perm(21) = 21;
      out_perm(22) = 22;
      out_perm(23) = 23;
      out_perm(24) = 24;
    end % perm
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_unperm = unperm( ~ )
      % Evaluate the unpermutation vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_unperm = zeros(24, 1);
      out_unperm(1) = 5;
      out_unperm(2) = 6;
      out_unperm(3) = 7;
      out_unperm(4) = 8;
      out_unperm(5) = 9;
      out_unperm(6) = 10;
      out_unperm(7) = 1;
      out_unperm(8) = 2;
      out_unperm(9) = 11;
      out_unperm(10) = 3;
      out_unperm(11) = 4;
      out_unperm(12) = 12;
      out_unperm(13) = 13;
      out_unperm(14) = 14;
      out_unperm(15) = 15;
      out_unperm(16) = 16;
      out_unperm(17) = 17;
      out_unperm(18) = 18;
      out_unperm(19) = 19;
      out_unperm(20) = 20;
      out_unperm(21) = 21;
      out_unperm(22) = 22;
      out_unperm(23) = 23;
      out_unperm(24) = 24;
    end % unperm
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( ~, ~ )
      % Evaluate the veiling vector.

      % Extract properties
      % No properties

      % Extract inputs
      % No inputs

      % Evaluate function
      % No body

      % Store outputs
      out_v = zeros(0, 1);
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % Test_03

% That's All Folks!
